### ISSUE TITLE
Compile with gccgo

### ISSUE THREAD

**Issue by awesomebing1** [asciinema/asciinema#100]
I have a PowerPC computer, and Go doesn't natively support my platform. However, gccgo does. Is there any way to compile this with gccgo, or if not, any plans to support this? I know that most people have the native Go compiler available, so this wouldn't be useful to most people.

Just messing around, I've gotten this:

gccgo github.com/asciinema/asciinema/main.go -o bin/asciinema
github.com/asciinema/asciinema/main.go:9:82: error: import file ‘github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go’ not found
github.com/asciinema/asciinema/main.go:10:36: error: import file ‘github.com/asciinema/asciinema/api’ not found
github.com/asciinema/asciinema/main.go:11:41: error: import file ‘github.com/asciinema/asciinema/commands’ not found
github.com/asciinema/asciinema/main.go:12:37: error: import file ‘github.com/asciinema/asciinema/util’ not found
github.com/asciinema/asciinema/main.go:105:6: error: reference to undefined name ‘util’
github.com/asciinema/asciinema/main.go:110:14: error: reference to undefined name ‘util’
github.com/asciinema/asciinema/main.go:116:9: error: reference to undefined name ‘api’
github.com/asciinema/asciinema/main.go:117:13: error: reference to undefined name ‘docopt’
github.com/asciinema/asciinema/main.go:121:14: error: reference to undefined name ‘util’
github.com/asciinema/asciinema/main.go:126:10: error: reference to undefined name ‘commands’
github.com/asciinema/asciinema/main.go:131:10: error: reference to undefined name ‘commands’
github.com/asciinema/asciinema/main.go:136:10: error: reference to undefined name ‘commands’
github.com/asciinema/asciinema/main.go:140:10: error: reference to undefined name ‘commands’

**Comment by sickill** [comment]
Unfortunately I have zero experience with gccgo. I'm afraid I won't be able to help with this at the moment. But feel free to post the status of your messing around here. It may be worth to putting the instructions for compiling on PowerPC on wiki.

**Comment by awesomebing1** [comment]
I unfortunately no longer have the same environment on my PowerPC computer, so I can no longer mess around with this.
