### ISSUE TITLE
UTF-8 native locale on OS X

### ISSUE THREAD

**Issue by nevalla** [asciinema/asciinema#103]
When I try to run `asciinema rec` I will get the following error
```
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.
```
Output of `locale` command by default is 
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
I tried to modify my locale settings as following:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```
But it did not help.

What part should I modify in order to get asciinema run properly?

UPDATE: Tried to install from Homebrew, and version 0.9.9 worked correctly, but after upgrading it to version 1.0.0 I got the error back

**Comment by sickill** [comment]
It's about `LC_CTYPE`. asciinema expects it to be in format `xx_XX.UTF-8` like others. It may be wrong assumption though, I'm now trying to find information if `"UTF-8"` is correct.

**Comment by nevalla** [comment]
Just upgraded to version 1.1.0 and it's working now as expected :+1:

**Comment by sickill** [comment]
Thanks for feedback!

**Comment by thekalinga** [comment]
How can I update these variable without hacking with the environment variables?

**Comment by sickill** [comment]
@thekalinga You can run `LC_ALL=en_IN.UTF-8 asciinema rec`.

**Comment by JulioPapel** [comment]
Just go to Terminal > Preferences > Profiles > Advanced 
- Set: Text encoding to: Unicode (UTF-8)
- Check: Set locale environment variables on startup.

**Comment by nic** [comment]
On iTerm:

![captura de tela 2018-03-25 as 17 40 53](https://user-images.githubusercontent.com/66042/37879735-c0f74f76-3053-11e8-84cd-80f78284f6ec.png)
