### ISSUE TITLE
voice frames

### ISSUE THREAD

**Issue by jfmc** [asciinema/asciinema#104]
It may be a nice feature the possibility to record and play voice frames (which use text-to-speech commands or subtitles). I've made a naive implementation (only for player and mac) here: https://github.com/jfmc/asciinema/commit/16cd7888b98cde1fefe5481a02e466b3375eab3d

**Comment by sickill** [comment]
Thanks. There is no plan to add "voice" support to asciinema recorder. However asciinema web player will get hooks (and maybe ability to play user provided mp3/ogg): https://github.com/asciinema/asciinema.org/issues/63#issuecomment-76848338

**Comment by jfmc** [comment]
Would it be acceptable to embed captions (https://en.wikipedia.org/wiki/Subtitle_(captioning)#Subtitle_formats) inside .json files for asciinema records?

**Comment by sickill** [comment]
I think that's interesting idea. That would require rethinking asciicast format, so it would need to go in future asciicast v2 format. I'm not fully sold on adding this at the moment, but thanks for bringing this up.

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if you still think this is a valuable feature worth maintaining.

**Comment by yaitskov** [comment]
These days some AI can read text
