### ISSUE TITLE
Install instructions for OS X fail.

### ISSUE THREAD

**Issue by redpola** [asciinema/asciinema#106]
bash$ curl -sL https://asciinema.org/install | sh
Downloading asciinema v1.1.1 for darwin-amd64...
######################################################################## 100.0%
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Warning: you may be asked for administrator password to save the file in /usr/local/bin directory
Installing to /usr/local/bin/asciinema...
Password:
cp: /var/folders/_f/p07k11_529g22zg7rmnmg_yh0000gn/T/asciinema-tmp.oCXU9G3a/asciinema*/asciinema: No such file or directory
Error: couldn't copy asciinema to /usr/local/bin/asciinema

**Comment by redpola** [comment]
Ok, so the problem here is that curl is failing because of the certificate problem. Adding the -k flag to the curl call fixes the problem. I'll leave it here for the maintainers to decide what to do.

**Comment by sickill** [comment]
Is this issue with asciinema.org certificate or github.com one?

**Comment by redpola** [comment]
I have no idea. What does the script attempt to connect to?

**Comment by sickill** [comment]
Script connects to github. You can download it first, then ran with verbose output like this:

    bash -x install

**Comment by svalleru** [comment]
I am hitting same issue even with -k/--insecure flag:

My OS: Darwin foo.local.com 14.4.0 Darwin Kernel Version 14.4.0: Sun Apr 19 20:30:19 PDT 2015; root:xnu-2782.30.2~2/RELEASE_X86_64 x86_64

**Comment by sickill** [comment]
Does this command trigger certificate error for you?

    curl -sL -O install https://asciinema.org/install

**Comment by redpola** [comment]
I think I created some confusion. When I added the -k flag **to the curl invocation in the install script** the problem was solved for me. I did not need the flag on the command line.

**Comment by sickill** [comment]
Then it's a problem with github.com certificate, or your OS (as I actually expect github to have the cert right).

Anyway, there's homebrew package so you can `brew install asciinema` instead of doing `curl/sh` thing.

**Comment by redpola** [comment]
OS X certainly seems to be more paranoid than whatever OS you're using.

Is there a macports version? I don't use brew.

Either way, this does not fix the problem as stated. The documentation needs updating or the problem otherwise resolving.

**Comment by svalleru** [comment]
Installing via  ```homebrew``` works fine; you might wanna be more thorough with your install script.

**Comment by sickill** [comment]
Ok, great. I'll try to detect OS X and display homebrew snippet as the recommended one.

**Comment by sickill** [comment]
@redpola there's macports version, yeah: https://asciinema.org/docs/installation

**Comment by redpola** [comment]
Great stuff. Thanks very much!
