### ISSUE TITLE
`^[[?1;2c` printed to terminal when playing locally

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#108]
Terminal itself is putting these characters on vim's stdin (emulating user typing them) during the recording, so vim can read and interpret them. It's a way of asking the terminal for its parameters. During playback asciinema sends the same escape codes that were emmited by vim but doesn't read from stdin so they stay in your prompt after asciinema finishes playback.

A potential solution would be to read everything from stdin during playback and ignore it.
Reading from stdin during playback would be also a good opportunity to add pause/resume functionality (space bar).

**Comment by mattdeckard** [comment]
I like the solution of reading from (and ignoring) stdin more than the solution I proposed in https://github.com/asciinema/asciinema.org/issues/239. It would also keep users from messing up the playback by accidentally hitting the keyboard during a playback.
