### ISSUE TITLE
[Feature request] Add parameter `--start-at NNN` to `asciinema play`

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#118]
While editing an ASCiinema file, it would be nice to be able to start a playback from a specific line or time into the recording. Example:

```
 asciinema play  --start-at 56s my.rec
 asciinema play  --start-at 3215l my.rec
```

would start the playback at 56 seconds after the original starttime, or at line no. 3215 of the JSON source file.

**Comment by parvbhullar** [comment]
Would like see that feature.

**Comment by sickill** [comment]
We now have #180 open for this.
