### ISSUE TITLE
[Feature request] Enable replacing existing ASCiinema movies by new, improved versions

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#119]
Please make it possible for the ASCiinema website to replace one version of a recording by a new one which has error corrections and other improvements **without assigning a new URL** to it. 

This way one could pass the URI of a cool asciicast around without fearing that it may become outdated.

A current workaround to update/improve a recording would be to delete the old version and upload a new one -- but this would also assign a new URI.

**Comment by sickill** [comment]
I'm not sure if replacing the recording "in place" is a good idea. What if I record something cool, then you embed it on your blog, then I replace it with some really not cool stuff and you show this not cool stuff your readers?

**Comment by KurtPfeifle** [comment]
> *"What if I record something cool, then you embed it on your blog, then I replace it with some really not cool stuff and you show this not cool stuff your readers?"*

What if I record something not-so-cool and riddled with one or two major errors/mistakes, then you embed it on your blog, then I improve/correct/fix it and make it awesome and you do not show this new cool stuff to your readers?

If you really are interested in my un-changed, un-corrected work, then embed it statically on your web site.

What if I published a v1.0 of some ASCiinema recording on asciinema.org and it becomes popular, then I discover a major flaw, or I make an update which is necessitated by an update to the software shown in the recording. I remove/delete the old version and replace it with a new one... Then I've lost also the popularity votes for the initial version, and the new one will be less visible.

***Every*** successful website which draws from user contributions lets the users freely edit and change user-contributed content. See StackOverflow/StackExchange. Without this feature, it would be half as successful...

Please re-think your objections again.

**Comment by sickill** [comment]
These are indeed valid points. I'm not sure what's more important (having "not cool -> cool" path vs not having "cool -> not cool" path), but I'll take it into consideration.

**Comment by KurtPfeifle** [comment]
What is the likelihood that someone who puts in the effort to update and change an existing ASCiinema screencast to end up following the *"cool -> not cool"* path?

Don't you want to trust the users of your cool software a bit more?   :-)

**Comment by sickill** [comment]
Like I said, I'll take this into consideration. I'm not saying "no". This may be a good idea, but I have more important things to think/plan in asciinema right now. I'm leaving the issue open so we don't forget about it.

**Comment by KurtPfeifle** [comment]
> *"I have more important things to think/plan in asciinema right now"*

That's OK, I don't want to rush it  :-)

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if you still think this is a valuable feature worth maintaining.
