### ISSUE TITLE
saving files locally without uploading

### ISSUE THREAD

**Issue by ivanov** [asciinema/asciinema#12]
it seems like this functionality is implied, but it does not work. If I hit "n" when prompted if I want to upload, the recording disappears

**Comment by sickill** [comment]
Hey everyone, good news.
First, you can now record to a local file and replay from it: http://blog.asciinema.org/post/one-point-o/
Second, all new asciicasts on asciinema.org are private by default so you can share them only with selected people (via secret URL): http://blog.asciinema.org/post/private/

**Comment by swdevbali** [comment]
Wait, it seems like we can't save recording to local file anymore, right?
I got Too many arguments error here

**Comment by sickill** [comment]
@swdevbali I assume you're either on Debian or Ubuntu and you installed asciinema from main repository. If that's correct than you most likely have asciinema v0.9.8, which is 3 years old, and doesn't have this ability.

**Comment by swdevbali** [comment]
Exactly!

I just install it via pip3, and it is awesome!

Thanks!
