### ISSUE TITLE
Support for `--silent` option

### ISSUE THREAD

**Issue by lenka21** [asciinema/asciinema#122]
right now before recording started I always see:

    ~ Asciicast recording started.
    ~ Hit Ctrl-D or type "exit" to finish.

and similar

    ~ Asciicast recording finished.
    ~ Press <Enter> to upload, <Ctrl-C> to cancel.

at the end.

it would be great to have a possibility of suppressing this messages. I have found, that simple redirecting the output doesn't work, because then nothing is displayed.

With that option I would have a possobility to record everything what other guys write on our common server. Simply enry in default `.zshrc` will do the job:

    exec asciinema rec $ASCIIHOME/`timestamp` -w 3 -y -s -c /bin/bash

**Comment by sickill** [comment]
That's a great idea, and seems to be easy to implement. Thanks!

**Comment by noisy** [comment]
@sickill: any ETA?

**Comment by sickill** [comment]
Um, no ETA, sorry. But I'm happy to accept PR :)

**Comment by noisy** [comment]
@sickill I do not know go yet :( And today, when I tried to just remove code responsible for printing this message, I had a problem to properly compile a binary. Regardless of [my changes](https://github.com/noisy/asciinema/commit/3af95d2e8d89564c2e06e9f661c68d49a6efaaa4), I always endup with version which produce this message. I am not sure how go building process works, but I am afraid, that somehow during build I unintentionally fetched original sources from last release tag.

**Comment by sickill** [comment]
It's in master. Can you pull and test it on your side?

**Comment by noisy** [comment]
@sickill it works as expected! Thanks! :)

**Comment by aksh7860** [comment]
Hi,
@sickill  is this feature available in asciinema version 2.0.2

**Comment by noisy** [comment]
Note: as

```
  -q, --quiet           be quiet, suppress all notices/warnings (implies -y)
```

option

**Comment by aksh7860** [comment]
But this doesn't suppress the warning at the start of asciinema

**Comment by aksh7860** [comment]
I mean this -q option do suppress the warnings and notices, but I wanted to suppress the message that is displayed at start and stop of asciinema

**Comment by aksh7860** [comment]
Hi @sickill @noisy 
Can you help here??
