### ISSUE TITLE
Atom.io plugin

### ISSUE THREAD

**Issue by balupton** [asciinema/asciinema#125]
Wondering what the feasibility is of having a atom.io plugin that can create casts for atom.io like how asciineema can for the terminal. Could asciineema be used for this? Would a new thing have to be created? Could WebRTC be used for it? Would https://github.com/pusher/atom-pair help?

**Comment by sickill** [comment]
asciinema records terminal and is strongly attached to the concept of terminal apps, ANSI control sequences and pseudo-terminals. Atom doesn't operate in this environment and building a recording plugin for it would be hard (and a big stretch).

Having said that it would probably be perfectly doable to build a recording plugin for Atom. It would record to a different format and would require a different player though. So asciinema wouldn't be a great help here.

**Comment by balupton** [comment]
Cool thanks for the info, will pursue this in other issues and link them here where needed.
