### ISSUE TITLE
[feature] Download backup

### ISSUE THREAD

**Issue by Fedjmike** [asciinema/asciinema#126]
- Ability to download asciicasts
- From the console and/or website
- In the native JSON format, or others (e.g. GIF, WebM)

Thanks!

**Comment by sickill** [comment]
You can download asciicast as:

* native JSON format: https://asciinema.org/a/22994.json
* png: https://asciinema.org/a/22994.png

**Comment by Fedjmike** [comment]
Cool! Add a link on the page of each asciicast?

**Comment by sickill** [comment]
Yeah, I guess it would be nice to add a link because it's not easily discoverable right now. Will do that.

**Comment by sickill** [comment]
There is a download button now on every asciicast page.
