### ISSUE TITLE
Theme Deactivates Upon Record

### ISSUE THREAD

**Issue by Rafeh01** [asciinema/asciinema#128]
# Terminal Theme Deactivates Upon Record
I am currently using Agnoster from oh-my-zsh as my theme. It has a very beautiful UI and as soon as my asciinema rec starts, my terminal reverts to default color scheme and bland text. Not sure why?

[![asciicast](https://asciinema.org/a/25400.png)](https://asciinema.org/a/25400)

* Theme: `Agnoster` (from oh-my-zsh)
* Using: `iTerm2`
* Operating System: `Mac OS X 10.10.1`
* Powerline Fonts Installed: `12pt Meslo LG L Regular for Powerline`

**Comment by sickill** [comment]
Is it the same when you start recording with `asciinema rec -c "zsh -l"` ?

**Comment by Rafeh01** [comment]
[That Worked!](https://asciinema.org/a/25689)
On my iMac, it just worked with `asciinema rec`. It only gives problems on my MacBook.
Thank you so much for your help!
https://asciinema.org/a/25689

**Comment by sickill** [comment]
For an explanation see "Why my shell prompt/theme isn't working during recording?" in the [FAQ](https://asciinema.org/docs/faq).

**Comment by ericmjalbert** [comment]
The FAQ link above is broken. Nowadays use: https://discourse.asciinema.org/t/why-my-shell-prompt-theme-isnt-working-during-recording/21 instead
