### ISSUE TITLE
[Feature Request] Pausing and resuming

### ISSUE THREAD

**Issue by SirPython** [asciinema/asciinema#129]
Occasionally, during a recording, I may want to take a break/look something up, which would create a long time of nothing happening in the recording. Or, I may have to enter sensitive information.

Either way, it would be nice to have the ability to pause or resume. For example, if I have to go look something up, I would type something like:

    asciinema pause

Then, when I'm done looking up whatever I was looking up, I would type something like:

    asciinema play

**Comment by sickill** [comment]
It's not really possible to pause the recording session. asciinema records all terminal output, which is incremental by nature. What you see on your screen is an interpretation of a series of commands, each building on the previous one. By skipping some of them (by doing "pause") we're risking losing some important escape codes that contribute to the displayed content.

However, if you want to shrink "long time of nothing" then you can use the `-w` switch, i.e. `asciinema rec -w 2`.
