### ISSUE TITLE
Save stdin commands .sh or .batch file locally (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [asciinema/asciinema#132]
Now `asciinema rec data.json ` saves the `stdout` output at `"stdout": []`
So, Is it possible to save my stack's `stdin` commands locally?
For example:

```sh
$ asciinema rec --save script.sh
```

Regards

**Comment by sickill** [comment]
I'm a bit confused here. You would like to record input as well, or you would like to save the recording to a shell file...?

**Comment by joseluisq** [comment]
I would like to save my input commands only to a shell or batch file, not stdout.

For example:

```sh
$ pwd
$ ls -lah
```
To `save.sh`

```sh
pwd
ls -lah
```

**Comment by jakubjedelsky** [comment]
We call it `history` in linux :)

```bash
$ pwd
$ ls -lah
$ history | tail -2
 3283  pwd
 3284  ls -lah
```

**Comment by joseluisq** [comment]
Great idea :D but I would like to save batch commands too and the same time
asciinema  records my stuff :)

El jue., 3 de diciembre de 2015 8:29, Jakub Jedelsky <
notifications@github.com> escribió:

> We call it history in linux :)
>
> $ pwd
> $ ls -lah
> $ history | tail -2
>  3283  pwd
>  3284  ls -lah
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciinema/asciinema/issues/132#issuecomment-161639809>
> .
>
-- 

Atte.

Jose Luis Quintana | quintana.io

**Comment by sickill** [comment]
Take a look here for the discussion on stdin recording. In short, I don't have plans to support this soon, but it is on my todo list with a lower priority ("some day").

**Comment by joseluisq** [comment]
@sickill great, I hope "some day" mean "in near future" 
Regards.
