### ISSUE TITLE
Build on ppc64: undefined: _C_uint

### ISSUE THREAD

**Issue by awissu** [asciinema/asciinema#134]
Hi!

[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:11: undefined: _C_uint
[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:11: invalid expression unsafe.Sizeof(_C_uint(0))
[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:12: undefined: _C_int
[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:12: invalid expression unsafe.Sizeof(_C_int(0))
[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:39: undefined: _C_uint
[   38s] ../go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/kr/pty/pty_linux.go:48: undefined: _C_int

See more: https://build.opensuse.org/build/network/openSUSE_Factory_PowerPC/ppc64/asciinema/_log

**Comment by sickill** [comment]
I'm not really familiar with PPC arch systems but if anyone can look at this I'd be happy to accept a PR!

**Comment by sickill** [comment]
@awissu I just released v1.3.0 which is implemented in Python so it doesn't have a compilation step. Can you check it out? `sudo pip3 install asciinema`.

**Comment by awissu** [comment]
Thanks.
Fixed.
