### ISSUE TITLE
Add scrolling to web viewer

### ISSUE THREAD

**Issue by jbohren** [asciinema/asciinema#137]
It would be great if when the user used the scroll wheel on the web viewer, it scrolled up as if it were a real terminal window. This would be great for looking over output that might get printed really quickly.

**Comment by sickill** [comment]
Thanks for suggestion. However, this is issue tracker for asciinema recorder. Closing this one, feel free to open new one in player's issue tracker.

**Comment by wjwwood** [comment]
@jbohren did you ever create an issue on the other tracker? Could you link to it if you did?

I consider this a killer feature for this already awesome tool.
