### ISSUE TITLE
Javascript recorder with audio !

### ISSUE THREAD

**Issue by remisharrock** [asciinema/asciinema#139]
Hi there,
we've developed a custom ACE editor (https://ace.c9.io/) that records/plays the keystrokes and the audio within the editor.
The player synchronizes the audio and the keystrokes for the playback. Here is the project:
https://github.com/France-ioi/fioi-editor2
Anybody interested by improving our idea ?

- We would like to encode in mp3 directly in pure javascript instead of using transloadit (idea http://audior.ec/blog/recording-mp3-using-only-html5-and-javascript-recordmp3-js/ )
- we would like to be compatible with the asciicast format (https://github.com/asciinema/asciinema/blob/master/doc/asciicast-v1.md)
- we would like to add a clickable progress bar for the player
- we would like to be able to download the mp3 and the event file (JSON ?) after a record is finished
- we would like to be able to play with local/distant (with URL) mp3s and event files

any idea/suggestions welcome !
and any help would be much appreciated !

this is also related to:
https://github.com/asciinema/asciinema.org/issues/63
and
https://github.com/asciinema/asciinema-player/issues/12

**Comment by sickill** [comment]
Hey @remisharrock. The idea for your ACE based recorder sounds nice. However, I have a trouble understanding how does this relate to asciinema player...?

**Comment by remisharrock** [comment]
@sickill  absolutely right, I thought it could give you an example of how to record audio synchronized with text input to implement it for asciinema. But I absolutely agree with the simplicity of the HOOKS solutions https://github.com/asciinema/asciinema-player/issues/12 . You can close this issue ;-)

**Comment by sickill** [comment]
Ok, thanks.
