### ISSUE TITLE
Virtualenv gets deactivated.

### ISSUE THREAD

**Issue by iCHAIT** [asciinema/asciinema#141]
When I am inside my python repository and have a virtualenv activated and I run `asciinema rec`, the virtualenv gets deactivated (as expected). Is their a way to prevent asciinema from deactivating the virtualenv?

```sh
(env)➜  repo-name git:(master) ✗ 
(env)➜  repo-name git:(master) ✗ asciinema rec
~ Current terminal size is 143x38.
~ It may be too big to be properly replayed on smaller screens.
~ You can now resize it. Press <Enter> to start recording.
~ Asciicast recording started.
~ Hit Ctrl-D or type "exit" to finish.
```
Virtualenv `env` gets deactivated -

```sh
➜  repo-name git:(master) ✗
~ Asciicast recording finished.
~ Press <Enter> to upload, <Ctrl-C> to cancel.
```

**Comment by sickill** [comment]
Read the 2nd question in the FAQ: https://asciinema.org/docs/faq

**Comment by ywyt738** [comment]
The faq link is 404.
Which question is in faq now.

**Comment by sickill** [comment]
Current FAQ answer link: https://discourse.asciinema.org/t/why-am-i-getting-command-not-found-at-the-begining-of-the-recording-session/20
