### ISSUE TITLE
Build on OpenBSD:  undefined: Termios

### ISSUE THREAD

**Issue by ligurio** [asciinema/asciinema#144]
5.8 GENERIC.MP#1236

 $ go get github.com/asciinema/asciinema 
 # github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:10: undefined: Termios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:11: undefined: setTermios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:18: undefined: Termios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:19: undefined: Termios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:20: undefined: getTermios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:36: undefined: Termios
 source/go/src/github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:49: undefined: Termios
 # github.com/asciinema/asciinema/util
 source/go/src/github.com/asciinema/asciinema/util/copy.go:34: undefined: FD_SET
 source/go/src/github.com/asciinema/asciinema/util/copy.go:35: undefined: FD_SET
 source/go/src/github.com/asciinema/asciinema/util/copy.go:37: undefined: Select
 source/go/src/github.com/asciinema/asciinema/util/copy.go:47: undefined: FD_ISSET
 source/go/src/github.com/asciinema/asciinema/util/copy.go:72: undefined: FD_ISSET
$

**Comment by aerth** [comment]
Similar error building on netbsd :cry: 

```
# github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/creack/termios/raw
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:10: undefined: Termios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:11: undefined: setTermios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:18: undefined: Termios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:19: undefined: Termios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:20: undefined: getTermios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:36: undefined: Termios
Godeps/_workspace/src/github.com/creack/termios/raw/raw.go:49: undefined: Termios
# github.com/asciinema/asciinema/util
util/copy.go:34: undefined: FD_SET
util/copy.go:35: undefined: FD_SET
util/copy.go:37: undefined: Select
util/copy.go:47: undefined: FD_ISSET
util/copy.go:72: undefined: FD_ISSET
*** Error code 2
```

**Comment by sickill** [comment]
Looks like `creack/termios` lib doesn't support OpenBSD and NetBSD....

**Comment by sickill** [comment]
I'm not really familiar with *BSD systems but if anyone can look at this I'd be happy to accept a PR!

**Comment by ligurio** [comment]
These patches fix creack/termios and asciinema:
- https://bronevichok.ru/trash/0001-Update-creack-termios-lib-to-the-last-commit.patch
- https://bronevichok.ru/trash/0002-creack-termios-Allow-to-use-termios-struct-and-funcs.patch
- https://bronevichok.ru/trash/0003-Fix-compilation-on-OpenBSD.patch

But in rest we have a problem with undefined syscall.Termios:

```
-bash-4.2$ go build
# golang.org/x/crypto/ssh/terminal
../../../golang.org/x/crypto/ssh/terminal/util.go:27: undefined: syscall.Termios
-bash-4.2$
```

and I don't know how to resolve it.

**Comment by sickill** [comment]
@ligurio Thanks for the patches! I don't know how to resolve the last problem either.

Anyway, I just released v1.3.0. It solves this problem (and many others!) because it's implemented in Python (it's based on v0.9.8 codebase) so it doesn't have a compilation step. Can you check it out? `sudo pip3 install asciinema`.

**Comment by ligurio** [comment]
Works fine. https://asciinema.org/a/79462

**Comment by sickill** [comment]
Thanks! I'll update the site to so it says we support OpenBSD now :)

**Comment by ligurio** [comment]
Thank you!
