### ISSUE TITLE
Question / documentation: bashrc

### ISSUE THREAD

**Issue by fulldecent** [asciinema/asciinema#145]
I would like to record all shell sessions to files like:

 > ~/ShellHistory/history-asciinema-20160209T173337Z.json

What needs to be done in bashrc to make this happen? And is this implementation advice worth documenting for others?

**Comment by dflock** [comment]
This would probably get you most of the way there:

```bash
command_exists () {
    command -v "$1" &> /dev/null 2>&1 ;
}

if command_exists asciinema ; then
  mkdir -p ~/ShellHistory
  asciinema rec ~/ShellHistory/history-asciinema-$(date +"%Y%m%dT%H%M%S%Z").json
fi;
```

This defines as bash function called `command_exists`, then uses it to only run this if the command `asciinema` is available.

It then ensures that the `ShellHistory` folder exists, then starts recording to a timestamped file inside that folder.

**Comment by dflock** [comment]
Not 100% sure about this, but probably be careful to put this at the bottom of the `.bashrc` - I think that when the user types `exit`, the subshell will exit, and execution will continue at the next line of the `.bashrc` - i.e. it'll run the rest of the `.bashrc` file.

**Comment by sickill** [comment]
Note that asciinema spawns new shell process (`$SHELL` by default) so if you add `asciinema rec...` to your `.bashrc` it will most probably start spawning thousands of nested asciinema+bash processes, eventually crashing your machine.

`asciinema rec` sets `ASCIINEMA_REC` env var to `1`. This can be used to detect if the current bash session is being recorded and preventing `asciinema rec` to start. Something like this at the bottom of `.bashrc` could do:

```bash
if [[ -z $ASCIINEMA_REC ]]; then
  asciinema rec ......
fi
```

**Comment by fulldecent** [comment]
Thank you. These look great!
