### ISSUE TITLE
Strange rendering when recording vim

### ISSUE THREAD

**Issue by DuncanBetts** [asciinema/asciinema#147]
https://asciinema.org/a/2zqavz00sbzvumxwg742h3ozi

The commands entered once I was in vim were as discussed here http://vi.stackexchange.com/questions/6452/can-vim-write-incremental-lines-i-e-on-each-line-a-becomes-b-and-1-becomes-2

Hope this is helpful, great work with this by the way :+1:

**Comment by sickill** [comment]
You didn't tell what's strange about it so not sure where to look for a bug... ;)

**Comment by DuncanBetts** [comment]
Sorry you're right, "strange" isn't helpful at all.
At 0:03 when Vim loads, the last chars on each row aren't shown.
Then at 00:09 when Vim indicates to me the pair of square brackets in red, it covers the last two letters of the preceding word.
Then at and just before 00:23 when I select a column of chars, the preceding [g on each row disappear.
Does it appear this way for you?
To be clear, each of the things I mention here are different from what actually happened in my terminal, outside the recording.
I can make a further recording in Kazam or similar or give you more info about my browser etc, if it renders correctly for you.

**Comment by sickill** [comment]
Cool, what browser are you using?
Having a video showing the "proper" behavior, or a series of screenshots, would be *very* helpful to analyze the difference in display.

I rewatched the asciicast once again and I don't see what you described.
Can you maybe create a screenshots of your terminal vs asciinema.org for these cases so I can compare?

**Comment by DuncanBetts** [comment]
Browser Version Specifics:
http://pastebin.com/f52Tv2Q7
Plugin Specifics:
http://pastebin.com/49APFPgC

How it looks from here:
https://vimeo.com/155215739

Here's a video of how it should look:
https://vimeo.com/155216388

And, it's not just Vim:
https://vimeo.com/155215770

I tried playing some videos in Chrome (everything renders fine):
https://vimeo.com/155216660

**Comment by sickill** [comment]
Can you check now? I think it should look better now.

**Comment by DuncanBetts** [comment]
Yep :+1: looks great from here
