### ISSUE TITLE
Wide characters overlap when changing display modes 

### ISSUE THREAD

**Issue by polm** [asciinema/asciinema#149]
I am not entirely sure if this is me doing something wrong or a bug in asciinema, but take a look at [this](https://asciinema.org/a/bhplgeltag9bm6v5dqm88ea55). `東京` displays correctly when not highlighted, but when part of a match the second character overlaps the first or otherwise looks weird. This is not the case in my terminal (mintty), where things look fine regardless of match state.

The code writing to the pty is my [searchy](https://github.com/polm/searchy) using substack's charm library; if there's some info I can add to make it easier to check if this is an issue with asciinema please let me know.

**Comment by polm** [comment]
[Here](https://asciinema.org/a/37364) is a demo that shows the issue more clearly.

I just checked and asciinema playback also looks fine in the terminal, so I guess this is an issue with the web player and wide characters.

**Comment by sickill** [comment]
Yeah, I think I know what's happening here. Will prepare a fix soon. Thanks for reporting!

**Comment by sickill** [comment]
Looks good now for me. Can you confirm?

**Comment by polm** [comment]
Looks like that fixed it - thanks!
