### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by rberteig** [asciinema/asciinema#150]
A Windows console is a (quirky) ANSI terminal, bound up behind the Windows Console API. Assuming a recorder can be made, the existing asciicast file format should be capable of representing nearly anything a Windows Console application can do. The resulting recording should be as playable as any other.

The difficult trick is the recording. Has anyone put any thought or effort into building such a recorder for a Windows console?

Would a port of asciinema to Windows be possible?

**Comment by sickill** [comment]
asciinema records raw stdout output of a child process (shell by default). It doesn't "capture" the screen contents in any way. It captures what gets printed (including all escape/control sequences) and it does that using pseudo-terminal (pty). 

So far I didn't find any Windows terminal supporting pty but recently I stumbled upon http://babun.github.io . The page says: `Mintty is the console used in babun.`

Mintty page (https://mintty.github.io) says: `Similarly to other Cygwin/MSYS terminals based on pseudo terminal ("pty") devices (...)`, however there's a long discussion thread about related issue: https://github.com/mintty/mintty/issues/56

If someone finds a way to use pty on Windows (or something faking pty but giving us raw stdout stream) then we could approach asciinema-on-windows.

**Comment by mattn** [comment]
Are you interesting in native cmd support?

https://asciinema.org/a/0nsiofsbhypumh6vy5jx6wuog

But currently experimental.

**Comment by sickill** [comment]
@mattn whoa! Sure, I'm curious to hear how this was achieved.

**Comment by sickill** [comment]
For anyone interested in recording on Windows, @mattn has an experimental branch here: https://github.com/mattn/asciinema/tree/windows

**Comment by jromero2k** [comment]
Hi! Perhaps this project is useful? https://github.com/adoxa/ansicon

**Comment by andkirby** [comment]
Guys, can I use this tool in git bash for Windows?
I.e. in [MinGW](http://www.mingw.org)

**Comment by sickill** [comment]
@andkirby I heard it worked in bash under Windows but haven't tried myself.

**Comment by andkirby** [comment]
Rumors... :) Thanks.)

**Comment by masaeedu** [comment]
@sickill Was this closed because it's merged or because you don't plan to support it?

**Comment by sickill** [comment]
@masaeedu Thanks for your interest.

I don't plan to support Windows because:

- most pty-like solutions for Windows are hacks
- I don't use Windows and as a main asciinema developer I don't want to maintain it

At the moment I believe it's not worth it.

**Comment by sickill** [comment]
asciinema works perfectly fine under Win10 (WSL): https://asciinema.org/a/123255

**Comment by be5invis** [comment]
Recording Windows terminals really need hacks, AFAIK they **still** support to write to the console buffer directly with MOV instructions. @miniksa

**Comment by andkirby** [comment]
> At the moment I believe it's not worth it.

I guess, it worth it. I really would love to have it the pocket to make some video in Git Bash for Windows.

I just have lots of stuff to show. :)

**Comment by sickill** [comment]
@andkirby https://github.com/asciinema/asciinema/issues/150#issuecomment-305995768

**Comment by sickill** [comment]
@tajmone thanks for the summary of the possible options. I don't think we'll be able to use node-pty though, as asciinema is written in Python.

I'm not very much familiar with WSL - is this part of Win10, or this needs to be installed separately?

**Comment by tajmone** [comment]
> I'm not very much familiar with WSL - is this part of Win10, or this needs to be installed separately?

Me neither ... but from what I read, WSL can be optionally installed in Win 10, and it will then install parts from an actual Ubuntu distro. Since I already have Git Bash for Windows, which offer me all I need right now, I'd rather not install it until I know a bit more about it — WSL surely offers more tools than just Git Bash, and has a broader scope; but I guess it also takes up more space.

**Comment by fquinner** [comment]
@tajmone @andkirby A little late, but you can set different shells with Matt's fork using `COMSPEC=cmd`, `COMSPEC=bash` or `COMSPEC=powershell`. IMHO, COMSPEC would be the *right* windows variable to set for this sort of function. Example outputs below:

Cmd:
https://asciinema.org/a/r0UNULw8K5r0HV35kTLOatAbX

WSL Bash (launched from within standard terminal):
https://asciinema.org/a/XtLu8rh65uFekim1VbWamNcmh

Powershell:
https://asciinema.org/a/HttJNKCwM9Tb1NlVP5PFy6Ftx

Personally I think it works jolly well...

**Comment by tajmone** [comment]
Thanks a lot @fquinner ! I've read here and there about Matt's fork but didn't realize it had reached such an operative status. The links you provided clarified the situation.

I'll defiinitely look into it!

**Comment by raghavpuri31** [comment]
So asciinema, didn't run on Windows cmd, right?

**Comment by joelhandwell** [comment]
One other option is to open issue in https://github.com/Microsoft/console to add pty compatible API to cmd.

**Comment by joelhandwell** [comment]
@bitcrazed I went ahead and try to make an issue but already @be5invis submitted  https://github.com/Microsoft/console/issues/57 !

**Comment by mattn** [comment]
If you don't want workaround or hacks, go-winpty can be used for this.

https://github.com/iamacarpet/go-winpty

**Comment by Kristinita** [comment]
> https://asciinema.org/a/r0UNULw8K5r0HV35kTLOatAbX

> https://asciinema.org/a/HttJNKCwM9Tb1NlVP5PFy6Ftx

@fquinner, I'm sorry, could you write in detail, how you record these videos?

I try install and run @mattn fork on Windows, but I don't understand, how I can fix [**`No module named 'termios'` error**](https://stackoverflow.com/q/22941571/5951529).

Thanks.

**Comment by mattn** [comment]
Try to build like below:
```
go get -d github.com/mattn/asciinema
cd /path/to/your/gopath/src/github.com/mattn/asciinema
git checkout windows
go build
```

**Comment by Kristinita** [comment]
@mattn ,

```go
D:\>go version
go version go1.10 windows/amd64

D:\>go get -d github.com/mattn/asciinema
package github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go: cannot find package "github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOROOT)
        C:\Users\SashaChernykh\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOPATH)
package github.com/asciinema/asciinema/api: cannot find package "github.com/asciinema/asciinema/api" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\api (from $GOROOT)
        C:\Users\SashaChernykh\go\src\github.com\asciinema\asciinema\api (from $GOPATH)
package github.com/asciinema/asciinema/commands: cannot find package "github.com/asciinema/asciinema/commands" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\commands (from $GOROOT)
        C:\Users\SashaChernykh\go\src\github.com\asciinema\asciinema\commands (from $GOPATH)
package github.com/asciinema/asciinema/util: cannot find package "github.com/asciinema/asciinema/util" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\util (from $GOROOT)
        C:\Users\SashaChernykh\go\src\github.com\asciinema\asciinema\util (from $GOPATH)
```

Thanks.

**Comment by mattn** [comment]
Well, please do as I mentioned.

**Comment by mattn** [comment]
Sorry, it was my mistake. Please try again as above.

**Comment by Kristinita** [comment]
@mattn,

1. Can you make your version installation more simply? For example, `pip install asciinemawindows`.
1. I still can't install your asciinema version (yes, [**I set gopath**](https://github.com/golang/go/wiki/SettingGOPATH#windows-10)):

```go
D:\go\src\github.com\mattn\asciinema>go build
main.go:11:2: cannot find package "github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOROOT)
        D:\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOPATH)
main.go:12:2: cannot find package "github.com/asciinema/asciinema/api" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\api (from $GOROOT)
        D:\go\src\github.com\asciinema\asciinema\api (from $GOPATH)
main.go:13:2: cannot find package "github.com/asciinema/asciinema/commands" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\commands (from $GOROOT)
        D:\go\src\github.com\asciinema\asciinema\commands (from $GOPATH)
main.go:14:2: cannot find package "github.com/asciinema/asciinema/util" in any of:
        C:\tools\go\src\github.com\asciinema\asciinema\util (from $GOROOT)
        D:\go\src\github.com\asciinema\asciinema\util (from $GOPATH)
main.go:15:2: cannot find package "github.com/mattn/go-colorable" in any of:
        C:\tools\go\src\github.com\mattn\go-colorable (from $GOROOT)
        D:\go\src\github.com\mattn\go-colorable (from $GOPATH)
```

Thanks.

**Comment by sickill** [comment]
Please move discussion about mattn's fork installation issues to mattn's repo. Thanks! ;)

**Comment by sickill** [comment]
If you'd like to discuss Windows support in general please use asciinema's discussion forum: https://discourse.asciinema.org/
