### ISSUE TITLE
Tmux spilt windows?

### ISSUE THREAD

**Issue by lukehinds** [asciinema/asciinema#151]
I have seen a few people recording tmux spilt windows, but google is not pulling up results on how they are doing this. I have had a brief look at the code and args available, but can't see how its done.

All my attempts result in just a single window being recorded.

Anyone have any ideas on how to go about this?

**Comment by sickill** [comment]
You can do it the following way:

* setup your tmux session (tmux new, create splits etc)
* detach
* run `asciinema rec -c "tmux attach -t session-name"`

**Comment by sickill** [comment]
I guess it would be worth posting this as a short blog post or a wiki page.

**Comment by lukehinds** [comment]
Super thanks, this is very useful. I think a quick blog entry would be useful as google will pick it up!

**Comment by sickill** [comment]
Added wiki page about it here: https://github.com/asciinema/asciinema/wiki/Recording-tmux-session

**Comment by normen** [comment]
This doesn't seem to work anymore for me on MacOS 10.15.7 / Tmux 3.1c - I just get a black screen when I play the recorded file?
