### ISSUE TITLE
Debian 7 - Unable to locate package asciinema

### ISSUE THREAD

**Issue by jamatos** [asciinema/asciinema#153]
Hi.

debian-7-amd64-minimal  

~# apt-get update
...
~# apt-get install asciinema
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package asciinema

**Comment by sickill** [comment]
Do we know who was the maintainer of this Debian asciinema package? How can we contact him/them? v1.3.0 was just released so it's a good opportunity to bring it back to Debian.

**Comment by zanchey** [comment]
https://packages.debian.org/jessie/asciinema says it was gustavo panizzo <gfa@zumbi.com.ar> and it's still available in Jessie (Debian 8); I don't think it was ever in Debian 7 and it won't be possible to add it into the old archive.

You can probably get away with the Ubuntu Precise PPA:
```
echo "deb http://ppa.launchpad.net/zanchey/asciinema/ubuntu precise main" | sudo tee /etc/apt/sources.list.d/asciinema.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0xc746fdc5059aa560f82032cd9d2e234c0f833ead
sudo apt-get update
sudo apt-get install asciinema
```

**Comment by sickill** [comment]
Given we can't really do much about Debian 7 archive I'm closing it.
