### ISSUE TITLE
Fedora installation deprecated

### ISSUE THREAD

**Issue by Adrianzatreanu** [asciinema/asciinema#159]
Hello, I am a Fedora user and apparently on your website the command to install ``asciinema`` is ``sudo yum..``. This command is no longer used, Fedora uses dnf now. You may consider changing it to ``sudo dnf`` :)

**Comment by sickill** [comment]
@Adrianzatreanu thanks. So it should be `dnf install asciinema` ?

**Comment by Adrianzatreanu** [comment]
yes, that would fix it :)
