### ISSUE TITLE
[question] Where are the recordings stored?

### ISSUE THREAD

**Issue by abhisekp** [asciinema/asciinema#161]
Where are the recordings stored if I don't upload them when it asks?

Previously using `Version: 1.0.16` when recorded (but not uploaded)
Recently updated to `Version: 1.2.0-1`

**Comment by sickill** [comment]
They are stored in `$TMPDIR`.

**Comment by abhisekp** [comment]
@sickill but `echo $TMPDIR` gives me nothing. And when I `ls /tmp`, i don't see any asciinema files. At least nothing there seems like asciinema files. 

Just so you know, I was using `Version: 1.0.16` and recently upgraded to `Version: 1.2.0-1`.
I recoding using older version but didn't upload them.

**Comment by sickill** [comment]
We use `ioutil.Tempfile` (see here https://github.com/asciinema/asciinema/blob/master/commands/rec.go#L77), not sure where this would be on your system...

**Comment by abhisekp** [comment]
@sickill I don't know golang, can you please write a program to display the `os.TempDir()` output real quick and how to execute it?
Thank you.

**Comment by abhisekp** [comment]
OK. I wrote a mini program without learning Golang :smile: 

```go
// showTempDir.go
package main

import "fmt"
import "os"

func main() {
  var osTemp = os.TempDir()
  fmt.Printf("%s\n", osTemp)
}
```
```sh
➔ go run showTempDir.go 
/tmp
```
So my `os.TempDir()` points to `/tmp` which I checked earlier and also checked again but I didn't find any `json` files. Other files since Mar 25th are present but I couldn't find any trace of the asciinema recording which I recorded yesterday.

Please know that I recorded using older version i.e. `Version 1.0.16` yesterday.

Please confirm whether the recordings were saved if not uploaded or they were discarded in the older release. Also in the older version, I was unable to  execute command like this `asciinema -t "PGP Game" rec pgp-game.json`. It showed me error i.e. it didn't accept any filenames as the last arg. I also tried using `asciinema rec pgp-game.json` but meh ... nothing :expressionless: 

Anyway, this was a minor incident. 

And thanks for creating this awesome app :smiley: :+1:

**Comment by sickill** [comment]
What's version 1.0.16? There wasn't such release. Here are all released versions: https://github.com/asciinema/asciinema/blob/master/CHANGELOG.md

**Comment by abhisekp** [comment]
*huh?* How is that possible? I had that release (*at least that's what asciinema cli reported*).
This is going really creepy now. :fearful: 
I'm scared :scream:

**Comment by nmrao** [comment]
Having the same experience as @abhisekp  on ubuntu 16.04 with `asciinema 0.9.8`. It shows `Too many arguments` when I type command `asciinema rec test.json` for recording with filename. [Here is the recording](https://asciinema.org/a/8hszihrdf6dzoxajtkv94mpz5)

**Comment by sickill** [comment]
@nmrao yes, 0.9.8 is very old version and it doesn't support recording to a file. Unfortunately there's still no updated version in Ubuntu repository.

**Comment by nmrao** [comment]
Thank you @sickill for your prompt response with details. If there are instructions that can be used to apply the update manually, then I would be glad to update.

**Comment by sickill** [comment]
@nmrao the following should work to install asciinema from git checkout:

```
git clone https://github.com/asciinema/asciinema.git
cd asciinema
sudo python3 setup.py install
```

**Comment by nmrao** [comment]
Thanks.  I'll try.

**Comment by figuernd** [comment]
> They are stored in `$TMPDIR`.

For others searching for this answer: if you specify a file name it will save to the current working directory, not $TMPDIR.
