### ISSUE TITLE
Embedded asciinema into ReStructuredText README ignored on GitHub

### ISSUE THREAD

**Issue by deeplook** [asciinema/asciinema#162]
I'm trying to embed an asciinema into a ReStructuredText README using this snippet:

```
.. raw:: html

  <script type="text/javascript" src="https://asciinema.org/a/14.js" 
          id="asciicast-5xwfvcrrk09fy3ml3a8n67hep" async 
          data-autoplay="true" data-loop="false"></script>
```

When I convert this with `rst2html.py` the snippet appears fine in the resulting HTML, but after uploading the `README.rst` to https://github.com/deeplook/sparklines GitHub will simply not show it. Is this a limitation of GitHub and/or is there a workaround without using MarkDown?

**Comment by sickill** [comment]
Github doesn't allow `<script>` tags in the README. You can however use image link:

    <a href="https://asciinema.org/a/14?autoplay=1" target="_blank"><img src="https://asciinema.org/a/14.png" width="835"/></a>
