### ISSUE TITLE
Release npm package

### ISSUE THREAD

**Issue by jreinert** [asciinema/asciinema#164]
Currently the releases contain embedded dependencies (React) and there's no way to use them with react.js npm bower and such. I think an npm package would be most useful since it would make using the player with webpack powered projects possible. Npm would also take care of the dependencies.

**Comment by sickill** [comment]
Thanks for the suggestion. I was thinking about this for a while, but I don't have any experience with creating npm packages. 

Any pointers? I'm happy to accept a PR.

**Comment by jreinert** [comment]
I tried digging into this but it seems that cljs and npm are very incompatible. :/ I don't see a way to achieve this easily.

**Comment by sickill** [comment]
Closing it for now. If there's interest one can open new issue about it [asciinema-player issue tracker](https://github.com/asciinema/asciinema-player/issues).
