### ISSUE TITLE
Storage of asciinema API key in config file

### ISSUE THREAD

**Issue by samdmarshall** [asciinema/asciinema#185]
I would like to include my asciinema config file as part of my dot files that i keep in a public repo; the only thing stopping me right now is that it would embed my api key as plaintext. Are there any plans to allow for alternative methods of storing this value, such as environment variable, that would allow for asciinema to consume it without having to store it in the clear?

Thanks!

**Comment by sickill** [comment]
That's a nice idea!

**Comment by samdmarshall** [comment]
@sickill I have opened a PR addressing this issue, now waiting on that to be merged.

**Comment by sickill** [comment]
@samdmarshall thanks! I'll take a look shortly.
