### ISSUE TITLE
missing dependancy python3-pkg-resources

### ISSUE THREAD

**Issue by Xcess** [asciinema/asciinema#189]
this package is needed but not in dependencies. when installing on fresh debian jessie, you should manually install python3-pkg-resources otherwise it won't work.

**Comment by sickill** [comment]
Thanks for the report. I'm not a python packaging guru so I can't say how to best solve that. Anyone?

**Comment by Xcess** [comment]
I'm not a programmer either but I think we should add "python3-pkg-resources" to asciinema debian package dependencies. (only python3 is listed)
https://packages.debian.org/sid/main/asciinema
I will proceed to sending an email to the package maintainer if the issue is not resolved.

**Comment by sickill** [comment]
Thanks!

**Comment by Xcess** [comment]
I contacted the package maintainer and he clarified some stuff for me. I think there weren't an issue at all. I'll try to reproduce it again with things he said in mind. If there were still problems I'll reopen this.
Thanks

**Comment by sickill** [comment]
Awesome. Thanks for your time!
