### ISSUE TITLE
Different sizing for player before clicked.

### ISSUE THREAD

**Issue by rjb25** [asciinema/asciinema#191]
When you click on a terminal recording, it then resizes to it's appropriate size. Shouldn't it start at the real size? Is this intentional? Is there a way to disable this? NOTE: This is for the embedded player that reads json files.
Pre click:
![screen2](https://cloud.githubusercontent.com/assets/12534967/22537156/fac7da70-e8d5-11e6-986a-f14a11012e17.png)
Post click:
![screenshot](https://cloud.githubusercontent.com/assets/12534967/22537159/008ab5ae-e8d6-11e6-988e-0e2720d65090.png)
Also side note but related, there is no preview of the terminal video.

**Comment by sickill** [comment]
It's explained in player's README: https://github.com/asciinema/asciinema-player#cols
Just set `cols` and `rows` to the values of `width` and `height` from the JSON file.
