### ISSUE TITLE
asciinema: option -w not recognized. See 'asciinema --help'.

### ISSUE THREAD

**Issue by alexylem** [asciinema/asciinema#195]
I am on Raspbian Jessie Lite (latest) on a Raspberry Pi.
I installed with
```shell
$> sudo apt-get install asciinema
```
Here is the pb:
```shell
$> asciinema -w 2.0 rec installation
asciinema: option -w not recognized. See 'asciinema --help'.
```
http://asciinema.org/a/8q8rlvzmixji3nk7qa0u86zvn

Thanks for your help.

**Comment by sickill** [comment]
Raspbian probably has very old asciinema version. I guess 0.9.8.

**Comment by alexylem** [comment]
Got the desired version doing:
```shell
$> git clone https://github.com/asciinema/asciinema.git
$> cd asciinema
$> python3 -m asciinema
```
Maybe a hint on how I could use it directly invoking `asciinema`?
`python3 -m asciinema` only works from within `asciinema` repo.

**Comment by sickill** [comment]
You can install the latest version with pip: `sudo pip3 install asciinema`

**Comment by alexylem** [comment]
Thanks
