### ISSUE TITLE
Consider resizing terminal in `asciinema play`

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#198]
Given we know width/height of the terminal that was used during recording session, we can send `\e[18;24;80t` (replace 80 with actual width and 24 with height) to the terminal at the beginning of the playback.

This escape sequence is part of "Window manipulation" sequence family, described in [XTerm documentation](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html).

It isn't supported by all terminal emulators, but it seems to work with XTerm, Gnome Terminal, Terminal.app (macOS).

**Comment by sickill** [comment]
This could be a default behavior, with command line switch and config option to enabled/disable this.

**Comment by mattdeckard** [comment]
Thanks for adding this, @sickill . I didn't realize the recorder was in a different repo.
