### ISSUE TITLE
Add --append option for recording 

### ISSUE THREAD

**Issue by ledroide** [asciinema/asciinema#203]
I suggest a new feature : 
```
asciinema rec --append existing_file.json
```
It sounds self explainable to me : when you just recorded and saved an action, and you want to continue the action to the same recording from the same state of the terminal, then you append the recording to the existing file.

**Comment by sickill** [comment]
https://github.com/asciinema/asciinema/issues/127 has just been implemented, so appending to existing recording will now be an easy thing to implement.

**Comment by SeriousM** [comment]
How does the player behave when the dimension changes between the recordings?

**Comment by sickill** [comment]
@SeriousM it uses the terminal size from the initial recording.

I just realized it would be nice to display a warning message when you --append and current terminal size is different than the original 🤔
