### ISSUE TITLE
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.

### ISSUE THREAD

**Issue by ReSearchITEng** [asciinema/asciinema#206]
This is a reopen of #160. This is still failing, even on asciinema 1.4 , latest in epel for centos/RH v7.
```bash
$asciinema
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.
$locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
**SOLUTION:**
```bash
export LC_ALL=${LANG}
```

**Comment by sickill** [comment]
As I mentioned in #160, it's enough to only set `LC_CTYPE="*.UTF-8"`. If you do it then you can set `LANG` and other as you wish.

**Comment by cmoulliard** [comment]
This trick doesn't work on Macos

```
$ export LC_CTYPE="*.UTF-8"
$ export LANG=
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"

$ asciinema
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.
```

**Comment by sickill** [comment]
I think I wasn't clear enough, sorry about that. What I meant by `export LC_CTYPE="*.UTF-8"` is `export LC_CTYPE="en_US.UTF-8"` (or other specific locale). `*` was just a thought shortcut :)

**Comment by arielf** [comment]
Hello @sickill 

Thanks for writing this cool software.

Seems like this issue still exists in latest (fresh clone 2019-01-29, Ubuntu 18.04):
```
$ git clone https://github.com/asciinema/asciinema
$ cd asciinema
$ git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
$ env LC_CTYPE="en_US.UTF-8" python3 -m asciinema  rec
asciinema needs an ASCII or UTF-8 character encoding to run. Check the output of `locale` command.
```

When I set `LC_ALL=${LANG}` (was `C`) - the problem goes away.

I happen to have `LC_ALL=C` which should behave similar to ASCII.
If ASCII is allowed, perhaps `C` could be allowed as well?

**Comment by lifranc** [comment]
@sickill My musl infra borked and I then took an oath never to leave nixOS again. But we started an early fork to rebase nixOS on musl although I could take months before the switch we'll be able to test then. The whole locale situation is rather ugly right now so we'll look for a sane solution.

**Comment by p-alik** [comment]
setting `LC_ALL` solves the issue on NixOS also.

```bash
$ nixos-version 
18.09.2266.aabc61049c0 (Jellyfish)

$ asciinema --version                                                         
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.

$ LC_ALL="en_US.UTF-8" asciinema --version                                                                                                  
asciinema 2.0.1
```

**Comment by sickill** [comment]
2.0.2 was released with #302 fix. It now works fine on `C` and `*.UTF-8`. 

In case you run `env LC_CTYPE="en_US.UTF-8" asciinema ...` and it still doesn't work, it could be that your OS doesn't local files generated properly, and you may need to uncomment it in `/etc/locale.gen`, then run `sudo locale-gen`.

**Comment by sickill** [comment]
The check for character encoding happens here: https://github.com/asciinema/asciinema/blob/develop/asciinema/__main__.py#L53
It uses Python's built-in `locale` module.

@lifranc I'm not familiar with musl too much, and how musl-based Python builds implement the locale support, but I'm happy to add necessary changes to make it work under nixOS (or musl in general).

**Comment by lifranc** [comment]
@sickill nixOS doesnt use musl - our fork of it will. I'm not testing the musl stack currently, busy with other things. Musl doesnt have `local-gen`.

**Comment by Tanishq-Banyal** [comment]
Can't we just have a force override flag ?

I have tried everything but it still complains about locale.

**Comment by sickill** [comment]
The reason asciinema requires UTF-8 charset is so we don't need to deal with countless different char encodings when replaying the recording. If the charset is set properly for your shell then all programs you run inside asciinema session will output UTF-8. If we had a flag that overrides this check it would mean the output asciinema captures is not guaranteed to be UTF-8, which in turn could lead to garbage being saved in the output asciicast file. But I guess we could have such force override option that would be marked as "on your own risk".

**Comment by upstream-dmahlberg** [comment]
I'm experiencing the same issue. Running on Manjaro with the Snap package. A flag would be awesome.

**Comment by mathieu-aubin** [comment]
Try the simplest easiest solution of setting on the command line BEFORE the program call... as in;

`LC_ALL=en_US.UTF-8 asciinema rec -c 'locale'`

Set a shell alias for easy going

**Comment by sickill** [comment]
At this point I don't think there's any remaining bug in asciinema with regards to locale handling (requirement of UTF-8 charset is desired behavior), so I'm closing it.

**Comment by UrNightmaree** [comment]
The issue still going.

I have asciinema installed via package manager (Paru) in Arch Linux (Proot). Apparently the error about Locale being not UTF-8 or ASCII is happening in my Arch Linux.
```
~/project/startmux                                                   main ?1 3s 14:26:2
=> asciinema
asciinema needs an ASCII or UTF-8 character encoding to run. Check the output of `locale` command.
```
I've also tried `LC_ALL="en_US.UTF-8"` and others possible fixes, still it doesn't affect anything.
```
~/project/startmux                                                      main ?1 14:28:2
=> LC_ALL=en_US.UTF-8 asciinema
asciinema needs an ASCII or UTF-8 character encoding to run. Check the output of `locale` command.
```

**Comment by sickill** [comment]
@UrNightmaree What asciinema version do you have? What's the output of `LC_ALL=en_US.UTF-8 locale`?

**Comment by UrNightmaree** [comment]
@sickill Sorry for long response, here's the output.
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by sickill** [comment]
@UrNightmaree yeah, so you don't have `en_US.UTF-8` locale generated on your system. See here https://github.com/asciinema/asciinema/issues/206#issuecomment-473658629

**Comment by UrNightmaree** [comment]
@sickill Thank you, that fixed the issue. 😄
