### ISSUE TITLE
Merge recordings from multiple terminals to same file

### ISSUE THREAD

**Issue by suhailcheroor** [asciinema/asciinema#207]
I want to record all terminal tabs to a single file. Is it possible ?

**Comment by sickill** [comment]
This is not possible, sorry.

**Comment by Cj-bc** [comment]
I think we can do such work by using tmux(or other terminal multiplexer) in current version.
Just for reference, I leave sample:

https://asciinema.org/a/211083

**Comment by sickill** [comment]
Using terminal multiplexer like `tmux` or `screen` is the way to go here.
