### ISSUE TITLE
Can't upload by revoked the API token

### ISSUE THREAD

**Issue by LEXUGE** [asciinema/asciinema#208]
I've revoked the API token in my broswer.
And I run the ```asciinema auth```
I opened the link and it said successful.But when I refresh the page.It still revoked.
Now,I cna't upload my cast anymore.
Please help me.

**Comment by sickill** [comment]
After revoking the API token you should remove `token = ....` from `~/.config/asciinema/config`, and it will be re-generated when you run asciinema again.

**Comment by LEXUGE** [comment]
@sickill But when I remove it,and run```asciinema auth``` again.It give the link:https://asciinema.org/connect/

**Comment by LEXUGE** [comment]
It works when your remove the config file at all.
