### ISSUE TITLE
Feature: Add "show link" button to player

### ISSUE THREAD

**Issue by xearonet** [asciinema/asciinema#212]
As in title, I suggest a new feature.
Add "show link" button to player.
When we go on some page where embedded player is, there's no way to check link to asciinema.org.
When I want use in terminal `asciinema play <link>` command, it's impossible to find address.

**Comment by sickill** [comment]
I like this idea, however this is a feature that should be added to the web player, not to the recorder. We have separate repo for web player project (https://github.com/asciinema/asciinema-player), feel free to open issue there if you're still interested in this. Thanks!
