### ISSUE TITLE
Including `command` in asciinema recordings is a security problem

### ISSUE THREAD

**Issue by cemerick** [asciinema/asciinema#216]
I discovered that if I provide a command e.g. `asciinema rec -c 'export API_KEY=...; ./script.sh' output.json`, then that command will be included verbatim in `output.json` in the `command` slot. Now that I know this, I can take care to put sensitive information (like API keys, URLs for private services, etc) in a script or scrub the output to null out the `command` attribute, but I'd like to suggest that `command` be included only when explicitly requested.

**Comment by sickill** [comment]
Good catch. For some reason it never occured to me (and I am person who does care about privacy in general).

We can either disable it by default and add a switch + config file option like you suggested, or we can include `command` when recording to a file but drop it from JSON when uploading (both when uploading implicitly through `asciinema rec` or when doing it explicitly from local file through `asciinema upload file.json`).

**Comment by cemerick** [comment]
`rec` time is really when it matters; especially for those that are self-hosting the player (like me), the assumption is that you can just drop the JSON file anywhere as-is.

**Comment by sickill** [comment]
Fair enough. There's not _that_ much use for it anyway - we display it on the recording page in place of a title when a title was not explicitly set and the recording explicitly specified the command via `-c`.

**Comment by cemerick** [comment]
In that case, it seems like you want exactly the reverse of what you suggested: exclude when writing the file, but include when uploading?

**Comment by sickill** [comment]
This was solved in #234.
