### ISSUE TITLE
problem when adding asciinema to .bashrc

### ISSUE THREAD

**Issue by adamramadhan** [asciinema/asciinema#218]
ive follow https://github.com/asciinema/asciinema/issues/145 and put below code on top of my .bashrc

```
if [[ -z $ASCIINEMA_REC ]]; then
    whoami="$(whoami)@$(echo $SSH_CONNECTION | awk '{print $1}')"
    asciinema rec -q ~/history/history-$whoami-$(date +"%Y%m%dT%H%M%S%Z").json
    #alias exit='killall -9 asciinema && exit';
fi
```

if you see the above code, trying to record quietly and then stop when user type exit too log everything in the server but;

**the problem**

we need to type exit twice when we typein `exit` so its not quite again. tried with the `alias exit='killall -9 asciinema && exit'` but it does not exit good. is there a better solution to this?

**Comment by sickill** [comment]
@adamramadhan just add `exec` before `asciinema rec ...`, should help.

**Comment by adamramadhan** [comment]
and to stop it?

**Comment by adamramadhan** [comment]
thankyou very much for the time @sickill.  it does work!. but how does that work? and in the first exit it gave me two files should be one, then after it i login and exit again its good to go, only one file is new. let me debug for while

**Comment by sickill** [comment]
I think this should work just fine:

```
if [[ -z $ASCIINEMA_REC ]]; then
    whoami="$(whoami)@$(echo $SSH_CONNECTION | awk '{print $1}')"
    exec asciinema rec -q ~/history/history-$whoami-$(date +"%Y%m%dT%H%M%S%Z").json
fi
```

**Comment by adamramadhan** [comment]
yes i already add that and it work, just wonder how does the exec made it work. btw thanks again @sickill !

**Comment by sickill** [comment]
To auto-upload this should work:

```
exec asciinema rec -q -y
```

(with no filename specified)

**Comment by sickill** [comment]
And here's explanation of how `exec` works: https://askubuntu.com/questions/525767/what-does-an-exec-command-do

**Comment by adamramadhan** [comment]
so will it auto stop if the session logout?

**Comment by adamramadhan** [comment]
ok thankyou @sickill ill open an issue again if anything goes wrong, thankyou again for your time.

**Comment by 66545shiwo** [comment]
@sickill  hello , please may i ask you some questions about using `exec`?  
when i use  `exec  asciinema rec  /tmp/$USER-$(date +%Y%m%d%H%M%S).log  -q `  in my .bashrc ,  the sftp client will faild to be connect by this user.  

I also find that if something error with `exec asciinema` command in .bashrc ,  i can't connect my VM by ssh , it will exit directly.
thank you !

**Comment by 66545shiwo** [comment]
> @sickill hello , please may i ask you some questions about using `exec`? when i use `exec asciinema rec /tmp/$USER-$(date +%Y%m%d%H%M%S).log -q ` in my .bashrc , the sftp client will fail to be connected by this user.
> 
> I also find that if something error with `exec asciinema` command in .bashrc , i can't connect my VM by ssh , it will exit directly. thank you !

hello，i solved the first question by restarting the sshd server.

the second question ,  something error means that  python version mismatching or `rec /dir` the dir doesn't have rights or the disk space is full and the record can't be written or etc.

**Comment by 66545shiwo** [comment]
> 

to the second question, i can login by  safe mode to solve those problems. 
all right , i have no question.
