### ISSUE TITLE
Run shell as a login shell?

### ISSUE THREAD

**Issue by ku1ik** [asciinema/asciinema#22]
I noticed on many asciicasts that people explicitly source .bash_profile to get their colored prompt, functions and other handy stuff.  Some people even get errors printed because their prompt uses some functions that they have defined in .bash_profile (prompt like other ENV variables gets inherited but functions not).

This is because recorder runs user's shell as interactive shell, but not as login shell.
Some terminal emulators run shell as login shell (with "-l" option), some not.
Recorder just does equivalent of `exec $SHELL` which translates to `exec /bin/bash` or `exec /bin/zsh`.

If there's a way in python script to check if the current shell in which it operates is a login shell we could use this information when spawning new inner shell. Getting the full command that was run to spawn user's current shell would also be helpfull.

**Comment by zenglian** [comment]
No no, not only simply pass `/bin/bash -l`, there are more steps in my case and I do not want to record those "init" steps.
