### ISSUE TITLE
asciicast v2: extra meta-data

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#223]
Some would like to have a place to store extra meta-data about the recording. I see the following options:

- use the env vars collection feature (see https://github.com/asciinema/asciinema/issues/222): put any extra info in new env vars and white-list these. Downside is that your shell and all apps started in it would inherit these env vars and this could potentially leak some sensitive data
- use any number of top-level, underscore prefixed keys, like `"_session_id": "67fds6futysgh"`, `"_my_internal_thing": "blah"` - the UNIX way, similar to `.` prefixed hidden files. You could add them manually / with a script, after recording is finished by editing the file, or the recording tool (e.g. castty) could add them automatically, prefixed with a tool name if it's tool specific thing (`_castty_audio_url`)
- use single top-level `meta` (or `prv`) object, with arbitrary tool/vendor/user-specific keys+values.

**Comment by dhobsd** [comment]
Another option would be to reserve a "meta" object for whatever custom keyspace a recorder wants to use.

**Comment by sickill** [comment]
This was also suggested by @XANi. Given that the whole header line is meta-data the key named `meta` in it doesn't feel right to me. I'd probably prefer something more specific like `prv` or `vendor`. Anyway, I updated the list above with this suggestion. Thanks @dhobsd !

**Comment by XANi** [comment]
"vendor" or "custom" makes sense

**Comment by josegonzalez** [comment]
`vendor` seems reasonable to me.

**Comment by sickill** [comment]
Not a priority, so closing for now.
