### ISSUE TITLE
asciinema rec filename complains about too many arguments

### ISSUE THREAD

**Issue by daixtrose** [asciinema/asciinema#225]
The docs state you can directly record to a file, but v0.9.8 does not recognize this option anymore and only provides the server option.

```bash
$ python3 -m asciinema rec test.json
asciinema: Too many arguments. See 'asciinema --help'.
```

**Comment by sickill** [comment]
0.9.3 is 3 years old version, which didn't have this ability. You should upgrade to newer one.

**Comment by daixtrose** [comment]
Strange. I checked out master ... will give it another try.

**Comment by Atrifex** [comment]
I am on `asciinema 0.9.8` and I still see this issue today. I installed using the `sudo apt install asciinema`. Looks like the repo might be out of date.

**Comment by sickill** [comment]
@Atrifex 0.9.8 is 3 years old version, which didn't have this ability. You should upgrade to newer one. 2.0 recommended.
