### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by stayingcool** [asciinema/asciinema#235]
Upload fails with the following error:
```
bash-3.2$ exit
exit
~ Asciicast recording finished.
~ Press <Enter> to upload, <Ctrl-C> to cancel.

~ Upload failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
~ Retry later by running: asciinema upload /var/folders/9g/60yjppb57779f3nrvxzvb_wn5wr3t6/T/tmp3zaagfuf-asciinema.json
```

**My Env:**
MacOS Sierra - 10.12.4 (16E195)

I'm able to play the recording, just that the upload fails. Any feedback or clues to fix this issue?

**Comment by boris** [comment]
@stayingcool I faced the same issue on El Capitan - 10.11.6 and fixed it by adding the `url` line to my `~/.config/asciinema/config`:

```
[api]
token = 123123123
url = http://asciinema.org 
```

**Comment by sickill** [comment]
@stayingcool which asciinema version and OS are you running?

**Comment by hickeng** [comment]
I'm seeing the same issue on current HEAD (8cdd2579ff2b192eca6df6b3164cabf03461aebe).
I'm getting `Error: HTTP status: 500 Internal Server Error` from `asciinema 1.1.1-56ee754` - the version installed by the `install` script when I ran that.

I get a successful upload when using `0.9.8`  which is what `apt-get` installed, but that doesn't allow me to upload already recorded files, or set the screen width to an appropriate size with tmux.

**Comment by sickill** [comment]
@boris @stayingcool that's a temporary workaround for client certificate issue, but we'll soon turn off http:// so we should look for the cause of `CERTIFICATE_VERIFY_FAILED` - I suspect some homebrew dependency issue wrt libopenssl or something similar.

**Comment by sickill** [comment]
@hickeng was the recording which fails produced by yet unreleased asciinema version? (`develop` branch)?

**Comment by hickeng** [comment]
@sickill yes, it was recorded with `develop`.

**Comment by sickill** [comment]
@hickeng ok, that's because `develop` produces version 2 asciicasts, and the instance at asciinema.org hasn't yet been updated to handle that. I'm going to fix that in the coming days.

**Comment by stefb12** [comment]
had the same issue with OSX Sierra 10.12.6 (16G29) and fixed it by editing ~/.config/asciinema/config as advised by @boris  (thanks !! :)
asciinema installed was performed directly using pip3:

$ pip3 install asciinema
Collecting asciinema
  Downloading **asciinema-1.4.0.tar.gz**
... (snip'd)

**Comment by boris** [comment]
I also installed 1.4.0 using pip3 on OS X I mentioned above. Sadly (to replicate this issue, but luckily to me) I'm not using OS X anymore and asciinema works pretty well in Linux :)

**Comment by sickill** [comment]
@stayingcool @stefb12 if you have installed Python via official dmg installer then you need to install root certificates by running this command:

    /Applications/Python\ 3.*/Install\ Certificates.command

Paste this into your terminal or locate and open in Finder.

(found this info here: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)

**Comment by stefb12** [comment]
thanks for the information @sickill !

**Comment by sickill** [comment]
@stayingcool has the above hint helped?

**Comment by Mariatta** [comment]
Hi, I'm having the same issue.
I'm on MacOS High Sierra 10.13.3 using asciinema 1.4.0.

The message I see is:
```
~ Upload failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:864)>
~ Retry later by running: asciinema upload /var/folders/xg/b8lym1jx549c9q1qc8cf7b0c0000gn/T/tmp8yro_585-asciinema.json
```

I tried running the suggested command above:
```
$/Applications/Python\ 3.*/Install\ Certificates.command
```
```
 -- pip install --upgrade certifi
Collecting certifi
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Installing collected packages: certifi
Successfully installed certifi-2018.1.18
 -- removing any existing file or link
 -- creating symlink to certifi certificate bundle
 -- setting permissions
 -- update complete
```
Upload still failed.

**Comment by Mariatta** [comment]
Ah nevermind, I had to update the `url` in `~/.config/asciinema/config` to http.
The upload works after I did that.
But feels like it should work over `https`?
Anyways, thanks!!

**Comment by bllyz** [comment]
okay but I dont have ~/.config/asciinema/config file .. what should I do ???

**Comment by bllyz** [comment]
can someone tell me what exactly the ~/.config/asciinema/config file has inside ?

**Comment by bllyz** [comment]
can someone tell me what exactly the ~/.config/asciinema/config file has inside ?

**Comment by bllyz** [comment]
can someone tell me what exactly the ~/.config/asciinema/config file has inside ?

**Comment by PlutoniumProphet** [comment]
@bllyz in the docs: https://asciinema.org/docs/config

I'm still broken on the pipe though

**Comment by ok-coder1** [comment]
Same issue here, but there was no config file so I made my own and after changing it to http, it gave this `asciinema: upload failed: HTTP status: 308`.
