### ISSUE TITLE
tmux recording gets messed up

### ISSUE THREAD

**Issue by madchap** [asciinema/asciinema#237]
Hi,

Great tool :)

I was trying from within a tmux, but as you see here, the output is a bit screwed up.
https://asciinema.org/a/139163

Any advices?

Thanks! I am spreading the word about this goodness ;-)
Best,
fred

**Comment by sickill** [comment]
@madchap I've moved this issue to player's issue tracker as this is playback/visual issue. Thanks for reporting!
