### ISSUE TITLE
Upload fails with "Broken Pipe"

### ISSUE THREAD

**Issue by pwoolcoc** [asciinema/asciinema#238]
Hello, I've been able to record & upload sessions before, but last night I started getting an error when uploading:

![image](https://user-images.githubusercontent.com/620392/31564083-9813e2bc-b02f-11e7-9cf0-dda4f8d227e7.png)

The file is still present at the path shown in the screenshot, and every so often I've tried re-uploading it, but get the same results.

My recording was a few minutes long, so I thought maybe it is too big? Here are the relevant stats:

![image](https://user-images.githubusercontent.com/620392/31564215-008f2b76-b030-11e7-8990-c4cbd8354ee7.png)

Also, my error is not quite the same as the one in https://github.com/asciinema/asciinema/issues/235, but I tried the fix from that issue anyway, with no change.

**Comment by pwoolcoc** [comment]
One more thing, since getting that error I have tried making new recordings (much shorter ones) and they upload just fine. Could it just be a file size issue?

**Comment by pwoolcoc** [comment]
@sickill it's about 13M

**Comment by sickill** [comment]
Yeah, so the instance at asciinema.org has a limit of 5MB. It's weird though you didn't get better error message, as we actually handle this case here: https://github.com/asciinema/asciinema/blob/develop/asciinema/api.py#L62 The server should nicely respond with 413 in this case. Maybe there's some proxy on the way which is killing requests with big payloads...?

**Comment by pwoolcoc** [comment]
@sickill not that I'm aware of. One time I tried it while connected to my work's VPN, but I also tried it while just on my regular home network. Same result both times.

**Comment by sickill** [comment]
Ok. What's the asciinema version this happens on? And what's your OS/distro?

**Comment by sickill** [comment]
@pwoolcoc If it's still an issue for you then let's dig deeper, you could try latest version from `develop` branch (https://github.com/asciinema/asciinema#running-latest-version-from-source-code-checkout).

Otherwise let's close it.

**Comment by richard-mauri** [comment]
I hit this today too ....

Richards-MacBook:vaultssh richardmauri$ asciinema --version
asciinema 2.0.1

Richards-MacBook:vaultssh richardmauri$ ls -lh /var/folders/4k/h9xhvv6j1yg6dzncz3r5s1x80000gn/T/tmps_0q0ve6-ascii.cast
-rw-------  1 richardmauri  staff   1.3M Dec 17 06:06 /var/folders/4k/h9xhvv6j1yg6dzncz3r5s1x80000gn/T/tmps_0q0ve6-ascii.cast

Richards-MacBook:vaultssh richardmauri$ asciinema upload /var/folders/4k/h9xhvv6j1yg6dzncz3r5s1x80000gn/T/tmps_0q0ve6-ascii.cast
asciinema: upload failed: <urlopen error [Errno 32] Broken pipe>
asciinema: retry later by running: asciinema upload /var/folders/4k/h9xhvv6j1yg6dzncz3r5s1x80000gn/T/tmps_0q0ve6-ascii.cast

**Comment by occivink** [comment]
Same here, I hit a 'broken pipe' with a 3MB file.

**Comment by sickill** [comment]
That was server-side issue. It's fixed now. Sorry for inconvenience!

**Comment by richard-mauri** [comment]
Thanks
I am again able to upload !

**Comment by binaryplease** [comment]
Having this error again, still an issue?

**Comment by lblasc** [comment]
Today I'm having the same issue, cast is only 1.2M big.

**Comment by sickill** [comment]
We related issue open, let's continue there: #335
