### ISSUE TITLE
[Feature request] Implement a "search" functionality on asciicast.org

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#239]
<sub>(Sorry, I don't know where else I can get this li'l feature request heard, so I put it here...)</sub>

----

User story:

> *"As a visitor to asciinema.org I am pleased to see that it hosts more than 20.000 asciicasts already. Congratulations."*
>
> *"Now I would like to be able to search for asciicasts on various topics. Or for asciicasts by specific users. I would like to find casts which have self-selected *'tags'* or *'keywords'*. I would also like to find those which make use of certain strings in their description."*

Author story:

> *"As an author of an asciicast I would like to be able to tell my friends to look at my latest cast. They know my username already, but without knowing a specific URL of one of my previous casts they will not be able to find it. They should be able to type in my user name in a search field to get a list of all my (public) uploads."*

**Comment by sickill** [comment]
Thanks for the idea! We have existing issue about this in server repository: https://github.com/asciinema/asciinema-server/issues/111 so you can follow it, and I'm gonna close this one.
