### ISSUE TITLE
Allow pausing playback

### ISSUE THREAD

**Issue by zeenix** [asciinema/asciinema#242]
While the server has supported this for a long time:

https://github.com/asciinema/asciinema-server/issues/127

it would be very nice to have this supported in the cmdline player as well.

**Comment by laughedelic** [comment]
Duplicate of https://github.com/asciinema/asciinema/issues/133. Also see https://github.com/asciinema/asciinema/pull/231

**Comment by sickill** [comment]
Toggling pause with space + stepping a frame at a time with period just landed in develop branch and will be released in 2.0 🙂
