### ISSUE TITLE
upload failed with <urlopen error [Errno 104] Connection reset by peer>

### ISSUE THREAD

**Issue by zaibon** [asciinema/asciinema#243]
Version used: 
```
asciinema --version
asciinema 1.4.0
```

When trying to upload a record I get :
```
▶ asciinema upload tmphuamwhek-asciinema.json
~ Upload failed: <urlopen error [Errno 104] Connection reset by peer>
~ Retry later by running: asciinema upload tmphuamwhek-asciinema.json
```

Here is the header of the record if it helps:
```json
{
  "height": 54,
  "command": null,
  "width": 199,
  "version": 1,
  "duration": 169.687237,
  "env": {
    "TERM": "xterm",
    "SHELL": "/bin/bash"
  },
```

**Comment by sickill** [comment]
Does it happen all the time or randomly? 
What OS/distro are you using?

**Comment by zaibon** [comment]
It happens consistently.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
```
 asciinema --version
asciinema 1.4.0
```

**Comment by sickill** [comment]
Can you try latest version from `develop` branch?

https://github.com/asciinema/asciinema#running-latest-version-from-source-code-checkout

**Comment by zaibon** [comment]
Ok, this version gave me more information why it fails
`Upload failed: Sorry, your asciicast is too big`

Didn't know they was a limit in size

**Comment by sickill** [comment]
Great, so we're further :)

Yeah, there's limit, we discuss it here if you're interested: https://github.com/asciinema/asciinema/issues/91

I guess we can close this one for now?

**Comment by zaibon** [comment]
Yep it's is solved. Thanks for the help
