### ISSUE TITLE
Recording command that exits quickly produces asciicast without event lines

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#246]
Recording `who`:

    asciinema rec -c who out.cast

Produces asciicast with only header line.

It seems the process (`who`) exits before asciinema manages to write stdout to a file, even though `who` prints text.

**Comment by LuckyDenis** [comment]
Good evening. I am interested in this problem. Can I add more information?

**Comment by bsene** [comment]
@sickill I tried the same recording:
`asciinema rec -c who out.cast`

Cast file contains all data and can be read within `asciinema`, so the issue seems to have been resolved maybe in recent versions.

PS: I tested it on MacOS(Mojave) environement

**Comment by sickill** [comment]
This has been fixed around 2.0.
