### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Bux42** [asciinema/asciinema#248]
Hello

I installed it at home, but on the Macs at my school, I have some issues due to permissions and stuff

`➜  asciinema git:(master) python3 -m asciinema --version
asciinema 1.4.0`

`brew install asciinema
Error: /Users/bux/.brew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:68: syntax error, unexpected ',', expecting keyword_then or ';' or '\n'
        You can install them, if desired, with:
                                         ^`
Also tried to install it from the github sources but then I have 

zsh: command not found: python3.6

**Comment by sickill** [comment]
I'm confused here... You run it via `python3 -m ...` and you get `brew install asciinema Error: ...` in output?

**Comment by Bux42** [comment]
`➜  ~ pip3 install asciinema
Collecting asciinema
  Using cached asciinema-1.4.0.tar.gz
Installing collected packages: asciinema
  Running setup.py install for asciinema
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/zz/zyxvpxvq6csfxvn_n0002_44000kj1/T/pip-build-ilhsspgu/asciinema/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/zz/zyxvpxvq6csfxvn_n0002_44000kj1/T/pip-ojbpa7w2-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/asciinema
    copying asciinema/__init__.py -> build/lib/asciinema
    copying asciinema/__main__.py -> build/lib/asciinema
    copying asciinema/api.py -> build/lib/asciinema
    copying asciinema/asciicast.py -> build/lib/asciinema
    copying asciinema/config.py -> build/lib/asciinema
    copying asciinema/http_adapter.py -> build/lib/asciinema
    copying asciinema/player.py -> build/lib/asciinema
    copying asciinema/pty_recorder.py -> build/lib/asciinema
    copying asciinema/recorder.py -> build/lib/asciinema
    copying asciinema/stdout.py -> build/lib/asciinema
    copying asciinema/term.py -> build/lib/asciinema
    copying asciinema/urllib_http_adapter.py -> build/lib/asciinema
    creating build/lib/asciinema/commands
    copying asciinema/commands/__init__.py -> build/lib/asciinema/commands
    copying asciinema/commands/auth.py -> build/lib/asciinema/commands
    copying asciinema/commands/command.py -> build/lib/asciinema/commands
    copying asciinema/commands/play.py -> build/lib/asciinema/commands
    copying asciinema/commands/record.py -> build/lib/asciinema/commands
    copying asciinema/commands/upload.py -> build/lib/asciinema/commands
    running install_lib
    creating /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/asciinema
    error: could not create '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/asciinema': Permission denied

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/zz/zyxvpxvq6csfxvn_n0002_44000kj1/T/pip-build-ilhsspgu/asciinema/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/zz/zyxvpxvq6csfxvn_n0002_44000kj1/T/pip-ojbpa7w2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zz/zyxvpxvq6csfxvn_n0002_44000kj1/T/pip-build-ilhsspgu/asciinema
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  ~ pip install --upgrade pip
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
➜  ~`

Sorry, I realized how confusing my first message was

**Comment by sickill** [comment]
What if you try `sudo pip3 install asciinema` ?

**Comment by Bux42** [comment]
I can't use sudo on those macs
It's at school unfortunately

**Comment by sickill** [comment]
This seems like some misconfiguration of Python and/or Pip, nothing to do with asciinema IMO.

**Comment by Bux42** [comment]
Okay so I found out that this existed:
`pip3 install --user asciinema`

Will install it in your $HOME repository

Do once it's done you should find the binary by doing:
`cd ~/Library/Python/3.4/bin`

Asciinema should be inside the bin folder, if not, change python version in the path
(maybe your version isn't 3.4 like me)

Then do an alias with the full path and voila!
