### ISSUE TITLE
[Feature request][v2] Please add a `--overwrite` parameter

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#249]
I've started to give a workout to v2.

One smallish thing, which still is able to annoy me:

1. I want to record to an existing file. However, I do not want to append to it, but to overwrite it. I get a warning *`asciinema: /path/file.asc already exists, aborting`*. (This, of course, is a good thing to have -- we do not want to blindly overwrite files.)

1. That means I have to use another shell command (*`rm /path/file.asc`*) in between of test recordings. It would be more convenient if I could just add a `--overwrite` parameter to do that instead, keeping the existing *good* default to not overwrite existing files.

**Comment by sickill** [comment]
I had a hunch this will be needed sooner or later :)

**Comment by AMR-KELEG** [comment]
I would like to work on this issue.
What I plan to do is:
1) add new command line argument in __main__.py (overwrite flag)
2) use os.remove(filename) in record.py if file already exists and overwrite flag is used

**Comment by KurtPfeifle** [comment]
Thanks, @AMR-KELEG & @sickill !
