### ISSUE TITLE
[Feature request] Record multiple tty at the same time

### ISSUE THREAD

**Issue by Bux42** [asciinema/asciinema#250]
Hi

Y'all know asciinema works (or uses) the script command (man script if you don't know it)

So the idea would be to add X arguments, being tty paths

It will then start recording those two (or more) terminals at the same time

After exiting (on the terminal that launched the recording), when pressing enter to upload, it would upload all the record files to the website

So the website should also support playing multiple recordings at the same time

Displaying all the recorded sessions on one page

I doubt much people would need this feature except me tho

**Comment by sickill** [comment]
Hey @Bux42!

That's interesting idea :) And yes, even though cool thing, I believe there wouldn't be many people using this to justify implementation and maintenance of this feature.

However, if you'd like to record multiple ttys, maybe you could [record tmux session](https://github.com/asciinema/asciinema/wiki/Recording-tmux-session) with multiple splits?

**Comment by Qix-** [comment]
TMux is not something I'd like to learn in order to record things, personally. I have a project right now that uses about 5 different panes and I'd love to be able to record all of them at once for a demonstration at work.

This would be really cool, to be honest. @sickill if you can point me in the right direction insofar as where changes might need to go, I can take a whack at this (unless some of it will require changes to closed source, of course).

I think about this feature _frequently_.

**Comment by masaeedu** [comment]
@sickill That would be great, but the tmux split workflow doesn't actually work in asciinema. asciinema-player and other renderers like termtosvg seem to garble recorded sessions that involve split windows in tmux. I suspect this is because screen clearing for a particular pane isn't getting propagated to the asciicast output somehow, but whatever the cause may be you usually end up with a jumbled overlap of characters that can't be understood.

**Comment by dsyer** [comment]
I'm not really a tmux expert, but it doesn't seem to work well at all with asciinema. The .cast only has one pane (the one I launched asciinema from). Am I doing something wrong?

**Comment by masaeedu** [comment]
@sickill Sorry I didn't get back to you about this before. Unfortunately I just stopped using the multi-pane workflow, so I don't recall what was going wrong.

@dsyer I believe the way to get multiple panes is to start asciinema directly in your terminal emulator (i.e. outside tmux) and then attach to your tmux session. See the link @sickill provided earlier in the thread that shows how to do this.

**Comment by Qix-** [comment]
FWIW years later and it's the lack of this feature that made me stop using asciinema.

**Comment by dsyer** [comment]
@masaeedu that works, thanks. I wish there was an easy way to skip the "tmux attach/tmux detach" at the beginning and end of the cast.

**Comment by synchro--** [comment]
Same here. Multi-tab recording session would be great but I guess I'll go for the tmux solution, then.

**Comment by sickill** [comment]
There's no simple way to implement recording of multiple shells (panes, tabs), other than using a multiplexer (tmux, screen). It would likely require rebuilding the whole tool from scratch, redesigning the asciicast file format etc.

**Comment by Qix-** [comment]
> There's no simple way to implement recording of multiple shells (panes, tabs), other than using a multiplexer (tmux, screen).

Sockets?

**Comment by sickill** [comment]
What do sockets solve?

**Comment by sickill** [comment]
Right, so it requires:

1. implementing the above,
2. creating new file format to keep output from multiple terminals in a single file, multiplexed,
3. implementing support for multiple terminals playback in web player,
4. implementing support for multiple terminals playback in `asciinema play`...

Thanks, but no thanks :)

**Comment by Qix-** [comment]
Not even if members of the community helped?...

**Comment by sickill** [comment]
I appreciate the offer but this not something that would justify the effort in my opinion. It would significantly complicate the codebases of cli, player, server, as well as tools people built around asciinema over the years, and at the of the day it would fall on the shoulders of the core team to maintain it for the years to come. This is a feature that very few users asked for and most of the ones who asked are happy with a tmux/screen based solution.

However feel free to experiment with this yourself, the source code is out there. Or maybe a good starting approach would be to build a set of tools on top of asciinema instead. e.g. a multi-recorder that uses multiple instances of `asciinema rec` under the hood, a multi-player that uses multiple instances of the web player, each embedded in its own UI tab.

**Comment by krisavi** [comment]
@ku1ik 
> @masaeedu I did many successful recordings of sessions with tmux involved, and it worked fine, so I'm surprised to hear you experienced problems here. Can you point me to an example session (on asciinema.org) which doesn't replay well in the web player but does ok when replayed in-terminal (`asciinema play filename.cast`)?

I have had issues with vertical panes, especially when the updates on them are happening like tail -f some log on one pane and doing something else on other. It keeps clearing and only updating part of the recording.
For example around 2 minute mark in here https://asciinema.org/a/dJGDAq7BwKpiUCCQL5O9R2eLZ . In terminal with asciiname play it works fine.
