### ISSUE TITLE
[Feature request for v2] Support re-playing asciinema casts with a timeline-offset

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#252]
When I did some post-editing of an ASCIInema v2 cast I'm currently experimenting with, it occurred to me that it would be very useful if I could use the (currently still imaginary) command line parameter   
 *`--offset <time>`* or   
 *` --offset <line>`*. 

Such a feature could be useful even beyond the mere editing of an asciicast file: you could directly point someone to a particularly interesting point in a replay, or even create a HTML link scheme for starting the re-play of an uploaded file on asciinema.org from that point.

**Comment by sickill** [comment]
There's already `?t=123` parameter supported on the site to start playback from given second (see "Customizing the playback section" in [sharing doc](https://asciinema.org/docs/embedding)).

For the in-terminal playback, we already have #201 opened for that, and there's old PR #180 which needs some work.
