### ISSUE TITLE
[v2] Mismatch of actual behavior of result to `asciinema rec -h` info re. `--stdin`

### ISSUE THREAD

**Issue by KurtPfeifle** [asciinema/asciinema#254]
*`asciinema rec -h`* says:

*`--stdin               enable stdin recording, disabled by default`*

However, when recording with *`asciinema rec one.cast`*, the recorded file contains:

```
[4.426335, "i", "e"]
[4.427224, "o", "e"]
[4.665514, "i", "x"]
[4.666192, "o", "x"]
[4.826479, "i", "i"]
[4.826958, "o", "i"]
[4.938407, "i", "t"]
[4.938787, "o", "t"]
```

indicating that stdin recoring is *enabled* by default. If this will be remaining for the final asciinema v2.0 release, there should be an option shown by the *`-h`* flag showing how to disable it.

**Comment by sickill** [comment]
@KurtPfeifle are you sure you don't have `stdin = yes` in `[rec]` section of your config file?

**Comment by KurtPfeifle** [comment]
@sickill:

Sorry, I cannot re-check on the same system. It was a VM which I had to delete due to space problems.

However, I suspect your guess was a very educated one: I checked again on two other systems, and could not reproduce the issue there.
