### ISSUE TITLE
Output recording to stdout

### ISSUE THREAD

**Issue by sindresorhus** [asciinema/asciinema#255]
Would be useful if `asciinema` had a flag to output the recording to stdout. This would make it easy to use the recording with other tools without having to write and then read a temp file.

This is what I currently have to do:

```
temp_file=$(mktemp); asciinema rec $temp_file --command="node example.js" --quiet; cat $temp_file | svg-term --out=screenshot.svg
```

This is how I'd like to use it:

```
asciinema rec --command="node example.js" --stdout --quiet | svg-term --out=screenshot.svg
```

Or just output to stdout if no filename is given.

This is the tool I'm using with `asciinema`: https://github.com/marionebl/svg-term-cli

// @marionebl

**Comment by sickill** [comment]
If you redirected `asciinema rec`'s stdout to a pipe then you wouldn't see what you're doing in your terminal ;) The stdout has to go directly to terminal emulator, without any redirects/captures. In other words it's impossible to achieve it with pipe.

But you can try this (works in bash, and probably in zsh too):

    asciinema rec -c "node example.js" >(svg-term --out=screenshot.svg)

`>(some command)` runs `some command` in a subshell, creates a file (pipe) at `/dev/fd/...` which is connected to this command's stdin, and then the whole `>(...)` expression is replaced with `/dev/fd/...` path :)

I did it with `wc -l`, which counted lines of the resulting recording, printing `27`:

```
bash-3.2$ asciinema rec >(wc -l)
asciinema: recording asciicast to /dev/fd/63
asciinema: press <ctrl-d> or type "exit" when you're done
bash-3.2$
...
...
bash-3.2$ exit
asciinema: recording finished
asciinema: asciicast saved to /dev/fd/63
      27
```

**Comment by chewi** [comment]
I tried the `>()` approach but it doesn't work now. It complains of an illegal seek.

**Comment by sickill** [comment]
That is an advanced bash trick, so it may not work in all cases.

**Comment by glaudiston** [comment]
Have you tried with `echo` and `jq` in bash ?:
```
echo -e "$(cat your-asciinema.json | jq '.stdout[][1]' | tr -d '"\n\r')" 
```

**Comment by sickill** [comment]
The improvements from https://github.com/asciinema/asciinema/pull/473 make it possible to do this:

```bash
asciinema rec --command="node example.js" --quiet /dev/stdout | svg-term --out=screenshot.svg
```

This will be released in v2.2.

**Comment by sickill** [comment]
Also I just merged #492 which allows use of `-` as the filename representing stdout, then piping the output to another tool:

```
sciinema rec --command="node example.js" - | svg-term --out=screenshot.svg
```

**Comment by sashaaro** [comment]
@sickill can you implement read terminal stdout steam via pipe without specify and run command 
```bash
bash -c "./install.sh" | asciinema rec "install.cast"
```
actually I need it for use pipe programmly while write extension for https://github.com/vercel/hyper
idea in background run asciinema and forward stream to asciinema like 
```js
var child = require('child_process');
var asciinemaProc = child.spawn('asciinema rec ...');

hyperTerminalStream.stdout.pipe(asciinemaProc.stdin, { end: false });
```

**Comment by sickill** [comment]
@sashaaro You can do it the other way around:

```bash
asciinema rec -c ./install.sh install.cast
```

Or if you explicitly want bash to execute the script (in case the script doesn't have shebang line):

```bash
asciinema rec -c "bash -c ./install.sh" install.cast
```

**Comment by sickill** [comment]
Closing this as support to record to stdout (by specifying `-` as output filename) was added in 2.2.0.

**Comment by sashaaro** [comment]
@sickill unfortunately https://hyper.is/ plugins api does not allow to replace shell, hyper run shell command himself. I need run asciinema in backround separately and have method to send termianl stream to asciinema. Lets do asciinema just receive terminal stream via stdin pipe
