### ISSUE TITLE
Audio recording, d'oh

### ISSUE THREAD

**Issue by pfalcon** [asciinema/asciinema#256]
How many stupid requests do you get? Not enough? Users are on the loose:

How can I add an audio recording to asciinema? Because you know, the purpose of recordings is oftentimes to teach/explain something, and that requires to comment on what happens on the screen.

**Comment by pfalcon** [comment]
Ok, this is fully addressed by https://github.com/dhobsd/castty . It also includes an alternative asciinema player implementation written in non-obscure language.

**Comment by pfalcon** [comment]
Cross-link to https://github.com/asciinema/asciinema-server/issues/63

**Comment by blashca** [comment]
"Stupid request" is the key phrase here. It's hard to believe that there are still people that cheeky. IT'S NOT YOUR PROJECT, MAN... So don't boss around and contribute instead of whining.

**Comment by LucasArruda** [comment]
It's because of haters like @pfalcon that I think Github should implement some sort of blocking feature where project owner could ban or block someone from contributing or even seeing a project.

Keep up the good work @sickill and mute/ignore the trolls.

**Comment by cipy** [comment]
ok, I might have sent the comment to the wrong product, here it goes again https://github.com/asciinema/asciinema-server/issues/63#issuecomment-1024532663
