### ISSUE TITLE
RFC asciicast v2: On-screen annotations

### ISSUE THREAD

**Issue by pfalcon** [asciinema/asciinema#257]
Why: Oftentimes, the purpose of screencast are teaching/tutorials. Just showing typed stuff and output is not enough.

Usecases:

1. Give a "title"/generic description of what happens on the screen. This is essentially a closed caption.
2. Pinpoint/explain a particular element on the screen.

While these are different usecases, they could be addressed by the same player UI element (though ideally CC-style annotations would be rendered in a way to note obscure screen content).

Proposed format:
~~~
{
  "duration": 10.0,
...
  "version": 1,
  "height": 24,
  "width": 80,
  "annotations": [
    {at:0.5, dur: 1, relx: 0.1, rely: 0.1, text: "annotation #1"},
    {at:3.0, dur: 3, relx: 0.8, rely: 0.8, text: "annotation\n#2"}
  ],
  "stdout": [
...
~~~

As can be seen, annotations blend well with v1 too.

An alternative format would be:

~~~
  "annotations": [
    [0.5, 1, 0.1, 0.1, "annotation #1", props: {}],
  ],
~~~

It's mandatory to support arbitrary annotation properties for extension and alternative players. `relx`/`rely` specify relative position of left top annotation corner, taking 1.0 as full terminal width/height.

FAQ:

Q: How are annotations shown at ascii terminal playback?
A: Generally, in no way. It's webcast feature. But interested parties may develop alternative players if they wish.

Q: How annotations being authored?
A: Manually. Though asciinema.org could offer an UI for that: during pause at needed place, press "Add ann" button, draw a rectangle over playback window, fill in text, set duration of annotation.

Simple reference implementation was posted as https://github.com/dhobsd/castty/pull/30

**Comment by beekhof** [comment]
Sad to see this closed without comment, its exactly what I'm looking for

**Comment by jpellman** [comment]
See #256 for the reason for why this was closed.  While the feature requests are legitimate, the OP was communicating with the project leads in an excessively condescending and adversarial tone for a product that he was paying absolutely nothing for.  Additionally, this request is a possible duplicate of https://github.com/asciinema/asciinema-server/issues/128.
