### ISSUE TITLE
PROMPT_COMMAND issue

### ISSUE THREAD

**Issue by indutny** [asciinema/asciinema#264]
Hello!

I've just updated to 2.0.0, and get this error every time I try to do a recording:

```
asciinema: press <ctrl-d> or type "exit" when you're done
sh: __prompt_command: command not found
sh-3.2$ exit
```

My `.bash_profile` has this:

```sh
export PROMPT_COMMAND=__prompt_command

__prompt_command() {
  local STATUS="$?"

  if [ $STATUS != 0 ]; then
    PS1="\w \[\e[0;31m\]$\[\e[0m\] "
  else
    PS1="\w $ "
  fi
}
```

Apparently `__prompt_command` got stripped out of the env, while `PROMPT_COMMAND` was preserved. Any way to fix it/work it around?

**Comment by sickill** [comment]
Hey! I think the problem here is login vs non-login shell. See the second question here: https://asciinema.org/docs/faq

**Comment by indutny** [comment]
It works, sorry for the noise!
