### ISSUE TITLE
SHA-256 mismatch for v2.0.0.tar.gz

### ISSUE THREAD

**Issue by ilovezfs** [asciinema/asciinema#270]
Homebrew users currently cannot build asciinema from source due to a SHA-256 checksum mismatch for v2.0.0.tar.gz (https://github.com/asciinema/asciinema/archive/v2.0.0.tar.gz)

Sun Feb 11 00:05:37 2018 -0800 the SHA-256 was
65224d8dcc8c579fd678fff83ea89eecfd35a1d2ca853ee6fcf27d2f7b5e3205

Now it's changed to
ef7c6143dfe1d3ae77fd5d41ef93344e0c5f840b1272a11f41938e1b718baf0f

Do you have any idea what happened here? To rule out malicious circumstances, we'll need to know why the file has changed before the checksum can be updated in Homebrew. Thanks!

**Comment by ilovezfs** [comment]
Ref https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19419/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/fetch_asciinema/

**Comment by sickill** [comment]
I have updated the `v2.0.0` tag. Specifically I've removed it and then created a new signed one.
Given that signed tags are more like commits this could have changed the checksum of the tarball...

**Comment by cp770077** [comment]
I have multiple devices

**Comment by sickill** [comment]
@ilovezfs has the checksum been updated in Homebrew? Can we close this?

**Comment by ilovezfs** [comment]
yup! Thanks :)

**Comment by sickill** [comment]
@ilovezfs well, thank you for handling this 👌
