### ISSUE TITLE
Invalid or revoked install ID

### ISSUE THREAD

**Issue by abaykan** [asciinema/asciinema#272]
I have record my Terminal, then when i press <enter>, this is what happened.
Any suggestion? I use MacOS btw. Thanks
```
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
asciinema: upload failed: Invalid or revoked install ID
asciinema: retry later by running: asciinema upload /var/folders/2f/0gzh45qs5rs7dfws_4pm5rz80000gn/T/tmp0jcz77i8-ascii.cast

```

**Comment by sickill** [comment]
What's your username on asciinema.org?
Have you used asciinema previously (versions older than 2.0)?

**Comment by abaykan** [comment]
my username: abaykan
And i've upload 1 record before. Then when i record another something, that is what happened.

**Comment by sickill** [comment]
Your recorder token has been revoked on 24th February. What you can do now is this:

1. remove file `~/.asciinema/install-id` (or `~/.config/asciinema/install-id`)
2. login on the website with your email
3. run `asciinema auth`
4. open printed URL

**Comment by abaykan** [comment]
It's worth. Thanks!

**Comment by p16andr** [comment]
@sickill @abaykan 
How to remove ~/.asciinema/install-id (or ~/.config/asciinema/install-id)

**Comment by abaykan** [comment]
@p16andr `rm ~/.asciinema/install-id` or `rm ~/.config/asciinema/install-id`

**Comment by p16andr** [comment]
@abaykan 
I get an error "no such file or directory"
Why?

**Comment by p16andr** [comment]
Do you know something?

**Comment by p16andr** [comment]
And when i run asciinema auth and go to the link tells me that "This token has been revoked"

**Comment by p16andr** [comment]
@sickill @abaykan
When i go to remove the file  rm ~/.asciinema/install-id or rm ~/.config/asciinema/install-id  i get an error "no such file or directory"  Why??  Do you know something??
