### ISSUE TITLE
Colorized bash prompt ignored ($PS1)

### ISSUE THREAD

**Issue by michael-o** [asciinema/asciinema#273]
I have a colorized bash prompt:
PS1='\[\033[01;32m\]\u@\h\[\033[0m\]:\[\033[01;34m\]\w\[\033[0m\]\$ '

When starting a recording, asciinema spits out:
    $ asciinema rec git-tutorial/test-session2.cast
    asciinema: recording asciicast to git-tutorial/test-session2.cast
    asciinema: press <ctrl-d> or type "exit" when you're done
    \[\033[1;32m\]\u@blnn719x\[\033[0m\]:\[\033[1;34m\]/net/home/osipovmi/public_html/protected\[\033[0m\]$ exit

Seems like bash prompts colors aren't supported?

Running asciinema 2.0.0 via FreeBSD ports. As well as "GNU bash, Version 4.4.19(0)-release (i386-portbld-freebsd10.4)".

**Comment by michael-o** [comment]
Seems like I am another idiot fooled by #22 and #53. While the FAQ contains [this](https://discourse.asciinema.org/t/why-am-i-getting-command-not-found-at-the-begining-of-the-recording-session/20), it is not first hand clear that it applies to `PS1`. Can FAQ be improved?

**Comment by sickill** [comment]
Yes, sure, I'll cover that in FAQ.

**Comment by michael-o** [comment]
Resolved via FAQ.

**Comment by ddfault** [comment]
FAQ moved to
https://docs.asciinema.org/faq/#why-am-i-getting-command-not-found-at-the-beginning-of-the-recording-session
