### ISSUE TITLE
Feature request: Add step back feature

### ISSUE THREAD

**Issue by Beercow** [asciinema/asciinema#278]
Much like pushing . to go forward through frames when paused. 
Something like , to go back one frame.

**Comment by sickill** [comment]
This is not possible right now, and it would require including full virtual terminal emulator inside asciinema recorder. See here: https://github.com/asciinema/asciinema/issues/133#issuecomment-316385321 

There's a lot of complexity with this, and I'm not sure if it's worth it. But you can always use [IPBT](https://www.chiark.greenend.org.uk/%7Esgtatham/ipbt/) for this :)
