### ISSUE TITLE
Demo video from the home page recording issue.

### ISSUE THREAD

**Issue by 1cedric2** [asciinema/asciinema#279]
The demo on the home page shows a link to a recording that is slightly different than the home page video itself.

This is my first ever contribution on GitHub. Hope this is a valid comment!

https://asciinema.org/a/17648
![image](https://user-images.githubusercontent.com/32031921/37554067-c4631216-29d3-11e8-8627-808d2aa749d3.png)
![image](https://user-images.githubusercontent.com/32031921/37554053-787d7ea4-29d3-11e8-9417-8ff88dd715b2.png)

**Comment by sickill** [comment]
@1cedric2 hey! Good catch :)

I never spotted this. I'm not sure why this happened, probably I was editing one of these recordings when preparing a release of new version, and made a mistake.

I plan to record new intro anyway, more up to date with current state of asciinema, so it's gonna be fixed soon.

**Comment by sickill** [comment]
Fixed.
