### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by KingAkeem** [asciinema/asciinema#280]
Hey i'm new to the project and I'd like to contribute. I was looking through the source code and noticed that there was almost no documentation. I'd like to go through and document the code for my first contribution. Possibly using a Google Style guide for documentation. Here  are examples of what it'd look like: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by sickill** [comment]
Hey Akeem! That sounds great. Indeed there's very little documentation of the functions. If you're still up for it then I'd be happy to receive some PRs. Let me know if you have any questions about the code!

**Comment by KingAkeem** [comment]
Awesome, thanks! I'm going to take a look now. I let you know if I have any questions, thanks again!
