### ISSUE TITLE
Ctrl-D to finish a recording does not work on certain Android devices (8.0 or later perhaps?)

### ISSUE THREAD

**Issue by fornwall** [asciinema/asciinema#295]
(I split out this sub-issue from #271)

After merging https://github.com/asciinema/asciinema/pull/294 the latest asciinema version now works on Android, and can be tried out by installing [Termux](https://termux.com/), running `pkg install asciinema` (the patch has already been applied to that package) to install it and then using it as normal.

Typing `exit` to finish the recorded shell works. Using Ctrl-D does not work, it just "hangs".

I reproduced the problem on the following devices:

- A Galaxy S8 running Android 8.0.
- A Nexus 6p running Android 8.1.

I cannot reproduce the problem on:

- A Sony z4 tablet running Android 7.1.

So the issue may be specific to Android 8.0 or later perhaps?

Note that the problem is not specific to asciinema 2.0, testing on 1.4 shows the same problem.

**Comment by edward-p** [comment]
Same issues on my  Nexus 6p whether Android 7.x nor 8.x, using lineageOS.

**Comment by Phakawanwijittra** [comment]
Well done

**Comment by sickill** [comment]
There were many improvements to how session ending is handled since 2.0, so if you have a chance please test latest 2.2.0. Or, if you don't have a need for this anymore, let's close it.
