### ISSUE TITLE
AppImage ("universal" Linux package)

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#296]
Anyone familiar with https://appimage.org/ ? Is it worth looking at to provide universal package for Linux?

**Comment by naeemrana2k** [comment]
https://youtube.com/channel/UCCj89gfDpKRnFJ46DSKYvWw

**Comment by om26er** [comment]
I don't have expertise in AppImage but if wanted, I can help with snap packaging, do let me know.

Also searching in the snap store, I found that asciinema is already published as a snap package by `sabdfl`, supposedly Mark Shuttleworth, so we can probably contact the snap store guys and reclaim the ownership if @sickill wants to support it officially.

try: `$ sudo snap install asciinema --classic`

I do commit to the maintenance of this snap (should there a problem arrive) at least for a few months.

Note: I am not associated with Canonical, though I am part of the snapcraft community.

**Comment by bittner** [comment]
I'm trying to do an AppImage for [PythonTurtle](https://github.com/cool-RR/PythonTurtle/) for some time (see also [1](https://github.com/cool-RR/PythonTurtle/issues/107#issuecomment-426899642), [2](https://github.com/cool-RR/PythonTurtle/issues/90#issuecomment-427168093)). It's looks easy, but a bit hard with Python, interestingly.

I'm still on it, though I may not do active troubleshooting right in the next few days. You can ping me how (if you don't hear from me for longer), and if I managed to get it going doing the same thing for Asciinema is probably just a matter of a few terminal commands and opening a PR.

**Comment by sickill** [comment]
The snap created by Mark was not updated in a long time, still at 1.3, which is ironic, since snaps are also supposed to improve roll out time. I removed snap method from listed installation options a while ago. 2.0 was released 9 months, and I really want people to use 2.0+ since it records in much improved file format. If we can have it updated to 2.0.1 then great. Most likely I won't have time to maintain it myself, but if there's anyone willing to (@om26er ?) then I'm happy to create a repo for it under asciinema organization.

**Comment by sickill** [comment]
@om26er that would be lovely. Is there any particular naming convention recommended/required for snap repos?

**Comment by markshuttle** [comment]
Happy to transfer publication of the snap to upstream, of course. Glad it proved a useful start :)

**Comment by sickill** [comment]
@markshuttle And I'm glad you found asciinema interesting enough to create the snap for it :)

I've created https://github.com/asciinema/asciinema-snap repo, and added @om26er and @markshuttle as collaborators to it. Feel free to push the original snap there, and update it when you have time. Thanks!

**Comment by om26er** [comment]
Cool, lets wait for Mark to push the existing source and I can then look to do a latest release.

**Comment by markshuttle** [comment]
My GH-fu wasn't up to getting code into asciinema/asciinema-snap, but I published into markshuttle/asciinema-snap instead. Feel free to either copy that into your repo or clone from there. I also updated to 2.0.1 and released that into the candidate snap channel so folks can test with 'snap install asciinema --candidate'

**Comment by markshuttle** [comment]
@om26er "supposedly" har har ;)

**Comment by markshuttle** [comment]
Ah, the issue was that I needed to accept the invitation to the other repo before pushing there.

**Comment by om26er** [comment]
Thanks @markshuttle, I cloned your code, made some changes and pushed it to https://github.com/asciinema/asciinema-snap

**Comment by sickill** [comment]
asciinema is available in pretty much every distro now via native package managers, and one can also install it with `pipx` on any OS so I'm closing this as I don't see immediate need for AppImage now.
