### ISSUE TITLE
 asciinema rec -w option missing

### ISSUE THREAD

**Issue by Lakshmipathi** [asciinema/asciinema#303]
Seems like recent version of  asciinema doesnt support `rec -w 2.5`. Is it replaced by other option or removed completely. If its a bug, please bring back that option.

**Comment by sickill** [comment]
The option has been renamed in 2.0. It's now `--idle-time-limit` or `-i` for short. All current options can be listed by running `asciinema rec -h`. Also, see here: https://github.com/asciinema/asciinema#rec-filename
