### ISSUE TITLE
.control-bar overlap video

### ISSUE THREAD

**Issue by fabiomontefuscolo** [asciinema/asciinema#304]
Hello,

The control-bar overlaps the video when we touch the mouse and it hides the bottom of terminal. Is it possible to place `.control-bar` below video box?

https://asciinema.org/a/zjEvIP2jpcQgXcvad05moyM9u

I didn't find other issue related to this. If it exists, very sorry!
Thank you!

**Comment by sickill** [comment]
Hey @fabiomontefuscolo. Yes, there's issue for that: https://github.com/asciinema/asciinema-player/issues/90 ;)
