### ISSUE TITLE
Uploading Progress

### ISSUE THREAD

**Issue by erayaydin** [asciinema/asciinema#309]
I think there should be a uploading progress when finished recording.

Its wait with:

```
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
^M
```

There should be progress:

```
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
**Uploading... %10**
```

**Comment by coryallen83** [comment]
Thanks

**Comment by erayaydin** [comment]
For example; [progress of python requests post](https://stackoverflow.com/questions/13909900/progress-of-python-requests-post)

**Comment by erayaydin** [comment]
Also, `async request`  will good for this project on large files

**Comment by sickill** [comment]
From my experience it usually uploads withing couple of seconds, if you don't have very big/long recording. I'm not super convinced it's worth it. Right now asciinema uses Python's built-in `urllib` for making HTTP request, and if we added progress indicator I'd rather find solution that works without extra dependencies (it's zero deps atm (😍), and I'd rather not ruin that (😆) by adding `requests` for progress).

**Comment by erayaydin** [comment]
`KISS` then :kissing_heart:
