### ISSUE TITLE
Add "terminal-recording" topic to this repo

### ISSUE THREAD

**Issue by katrinleinweber** [asciinema/asciinema#314]
As an educator, I'd like to be able to advertise the concept of creating animations from the terminal. Thus, I like to link to https://github.com/topics/terminal-recording instead of collecting a bunch of individual tool links.

How about `asciinema` joins the small club and also adds the topic `terminal-recording` to this repo?

**Comment by katrinleinweber** [comment]
PS: Same request for the [`asciicast2gif` repo](https://github.com/asciinema/asciicast2gif) ;-)

**Comment by sickill** [comment]
That's great idea Katrin 👍  I just added this topic to both repos.
