### ISSUE TITLE
asciinema changes my shell and env

### ISSUE THREAD

**Issue by zenglian** [asciinema/asciinema#319]
When I run asciinema, seems it exits from the current shell (bash) thus the shell is changed (to csh) thus the environment is changed.
I have to re-run "bash" and the init steps which produces tons of output which I do not want to record.
Can it be avoided?

**Comment by sickill** [comment]
Yes. See here:

- https://github.com/asciinema/asciinema#rec-filename 
- https://discourse.asciinema.org/t/why-am-i-getting-command-not-found-at-the-begining-of-the-recording-session/20 
- https://github.com/asciinema/asciinema#configuration-file

What does `echo $SHELL` print in your bash (when not recording)?
