### ISSUE TITLE
Error 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by javilinux** [asciinema/asciinema#323]
Hello,

I suppose it is just a temporary issue but I get a 503 error when I try to check the preview at:

https://asciinema.org/a/Yd8ej63FO4Yd05UofjBI1czep.png 

Although the full session works at:

https://asciinema.org/a/Yd8ej63FO4Yd05UofjBI1czep

**Comment by sickill** [comment]
No need to be sorry for reporting (even temporary) service interruptions :)
