### ISSUE TITLE
How to change the save folder?

### ISSUE THREAD

**Issue by fhefh2015** [asciinema/asciinema#329]
for example:

I want to save the record to the `$HOME/Documents/TerminalRecord`

How to change the ` temporary folder` to `my custom folder`?

Thanks!!

**Comment by vanyakosmos** [comment]
`rec` subcommand takes additional `filename` parameter, so you can specify desired destination like this: `asciinema rec ~/Desktop/foo.bar`

**Comment by sickill** [comment]
What @vanyakosmos said 👍
