### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by syahdeini** [asciinema/asciinema#331]
Hi I clone the asciinema repo, change the branch to master and install it
``` ~ git clone https://github.com/asciinema/asciinema.git\n
   ~ cd asciinema
   ~ python setup.py install
   ~ python3 -m asciinema --version
    >> asciinema 2.0.1
   ~ asciinema upload jajaja
   >> asciinema: upload failed: <urlopen error [Errno 8] nodename nor servname provided, or not known>
    asciinema: retry later by running: asciinema upload jajaja 
```
I tried to add url in ~/.config/asciinema/config. But it just doesn't work
I use macOS Mojave 10.14.1. any suggestion?

**Comment by sickill** [comment]
What is the output of `asciinema auth`? It should display a URL of the server.
Don't paste full URL here as it contains your installation ID (UUID) which should be kept private, the beginning of a URL will give us a hint on the problem maybe.
