### ISSUE TITLE
The server is having temporary problems

### ISSUE THREAD

**Issue by theScrabi** [asciinema/asciinema#332]
When I try to upload something using `asciinema upload <file>` it keeps telling me this
```
asciinema: upload failed: The server is having temporary problems. Try again in a minute.
asciinema: retry later by running: asciinema upload pwsh_profe.cast
```

this error now shows up for days.

I'm running asciinema 2.0.1 on linux.

**Comment by frogred8** [comment]
I'm having the same problem. Response status code is 500 internal error.  
Strangely, I can upload files only less than 10k.

**Comment by bondarewicz** [comment]
same here, works on small files...

**Comment by sickill** [comment]
That was server-side issue. It's fixed now. Sorry for inconvenience!
