### ISSUE TITLE
Sensitive data

### ISSUE THREAD

**Issue by fedeisas** [asciinema/asciinema#345]
I tried to get in touch with @sickill but couldn't find an email anywhere and couldn't get a response in Twitter.

I used to work for a company some years ago, I used asciicinema to share a session with a coworker without really thinking about the security implications of it. That session ended up showing up [here](https://github.com/0xbzho/asciinema.org-2015-03/).

While it doesn't leak any credentials, it does show sensitive information about the app tech stack, database, etc.

I don't seem to even have an account on https://asciinema.org/ (maybe I was using my work email?). 

Does anyone knows @0xbzho?

**Comment by cyc115** [comment]
Either way I think it would be good for @oxbzho to take it down and find out why it was there in the first place.

**Comment by fedeisas** [comment]
Seems like a ghost account. I contacted @github about it but they refuse to take it down.

**Comment by sickill** [comment]
It seems they crawled asciinema.org and downloaded all public recordings back then (2015, 2016).

I don't know this user either.
