### ISSUE TITLE
recover accidentally closed recording session

### ISSUE THREAD

**Issue by cyc115** [asciinema/asciinema#349]
Is there a way to recover lost recording sessions that was accidentally closed? I remember vaguely that the recording is somewhere in `/tmp` but could not remember exactly where. 

This happened quit a few times in the last few month and I've seen other issues that was brought up related to persisting recordings during a recording.

**Comment by sickill** [comment]
If you have asciinema 2.0+ then the recording gets writtent in real time to a file in `/tmp`. The file has a random name but always gets `.cast` extension, so you can `ls *.cast` or `find /tmp -name '*.cast'` to find all that weren't finished.
