### ISSUE TITLE
https://asciinema.org

### ISSUE THREAD

**Issue by Duchoadongland** [asciinema/asciinema#352]
@0xbitcoin

**Comment by endreszabo** [comment]
Yes this is a very serious issue. I also feel deeply concerned. asciinema owners should take immediate action. Marcin are you around?

/s

**Comment by sickill** [comment]
@endreszabo what's the issue? I don't understand.

**Comment by endreszabo** [comment]
> @endreszabo what's the issue? I don't understand.

Sadly (or not so sadly, depends on POV), there is no issue here, just a spam and a sarcastic comment on that. ”/s” indicates applied sarcasm :)

**Comment by sickill** [comment]
Hah, ok, I didn't get `/s` :) Yeah, the spam on GH is increasing.
