### ISSUE TITLE
github release of v2.0.2 missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [asciinema/asciinema#358]
there is a 2.0.2 tag, so github automatically shows it in the "releases" tab.

but the 2.0.1 is much more prominent as it was manually made (description and files added) and also 2.0.1 is advertised as "latest release".

https://github.com/asciinema/asciinema/releases

**Comment by sickill** [comment]
Good catch. Fixed now. Thanks.

**Comment by sickill** [comment]
Good catch. Fixed now. Thanks.
