### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by gaoxch** [asciinema/asciinema#361]
[root@fangzhen2]~# pip3 install asciinema
Collecting asciinema
  Downloading https://files.pythonhosted.org/packages/a7/71/771c859795e02c71c187546f34f7535487b97425bc1dad1e5f6ad2651357/asciinema-2.0.2.tar.gz
Installing collected packages: asciinema
  Running setup.py install for asciinema ... done
Successfully installed asciinema-2.0.2
[root@fangzhen2]~# asciinema rec
zsh: command not found: asciinema
[root@fangzhen2]~#

**Comment by cuamckuu** [comment]
Probably it's not in your PATH. 

Try running it with:
```python3 -m asciinema rec```
