### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by ritwik12** [asciinema/asciinema#366]
Following links are broken:

https://asciinema.org/ - Terminal session recorder and the best companion of asciinema.org.
https://asciinema.org/a/113463?autoplay=1 - VIDEO

**Comment by predragmandic** [comment]
@ritwik12 I can open both of those links without any problem. Check your firewalls.

**Comment by ritwik12** [comment]
@predragmandic I am not able to, could be a proxy or firewall issue. But since you say it's working. I will close it out
