### ISSUE TITLE
ASCIINEMA_REC is not set

### ISSUE THREAD

**Issue by omry** [asciinema/asciinema#372]
Looks like ASCIINEMA_REC is not properly set.
I found that if I run asciinema with this it will be passed to the recoded session:

ASCIINEMA_REC=1 asciinema rec

This seems to disagree with the doc (https://asciinema.org/docs/usage)

**Comment by Enteee** [comment]
asciinema 2.0.2 -- and I see the same issue.

**Comment by vext01** [comment]
Same issue here on OpenBSD.

**Comment by sickill** [comment]
Fixed via #400. Will be part of the upcoming release.

**Comment by mickael-menu** [comment]
Still happens for me with 2.0.2.

```
~ > asciinema --version
asciinema 2.0.2

~ > asciinema rec -c 'echo "ASCIINEMA_REC=$ASCIINEMA_REC"'
asciinema: recording asciicast to /var/folders/ks/ny2nfkh5183ffwm10fw_9rq80000gn/T/tmp2oid1izq-ascii.cast
asciinema: exit opened program when you're done
ASCIINEMA_REC=
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
```

**Comment by kabouzeid** [comment]
Indeed, the last release was almost 2 years ago.
