### ISSUE TITLE
Valid filenames can be misunderstood as http URL in `url_open`

### ISSUE THREAD

**Issue by s-leroux** [asciinema/asciinema#387]
`http:example.cast` is valid filename. But, given the code below from `url_open`, it seems it would be misunderstood as an HTTP URL:

https://github.com/asciinema/asciinema/blob/350d5e9d8b7cee1be5db4091815942c9d035e7dc/asciinema/asciicast/__init__.py#L45

Can someone confirm that?

**Comment by AemJane** [comment]
Avcisrs-aus.ea/s$
