### ISSUE TITLE
The Nose unittest library has reached end-of-life

### ISSUE THREAD

**Issue by s-leroux** [asciinema/asciinema#388]
From https://nose.readthedocs.io/en/latest/:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Unless there is a strong requirement for Nose features, may I suggest converting the tests to [the standard Python unittest](https://docs.python.org/3/library/unittest.html) library?

**Comment by sickill** [comment]
Converting tests to Python's standard library unittest sounds great 👍

**Comment by sickill** [comment]
Nose has been replaced with pytest in #445.
