### ISSUE TITLE
CentOS install

### ISSUE THREAD

**Issue by RockAfeller2013** [asciinema/asciinema#390]
Unable to install on CentOS

CentOS Linux release 7.7.1908 (Core)

sudo dnf install asciinema
sudo yum install asciinema

Both error - No match for argument: asciinema

**Comment by wkrik** [comment]
I got it working on CentOS 7.9 by doing the following:
1. Install python 3.x - https://linuxize.com/post/how-to-install-python-3-on-centos-7/
2. run: pip3 install asciinema

**Comment by sickill** [comment]
It seems EPEL has it for CentOS 8 https://centos.pkgs.org/8/epel-aarch64/asciinema-2.0.2-6.el8.noarch.rpm.html 
There's older 1.4 version for CentOS 7 in EPEL too.
