### ISSUE TITLE
Presentation mode, for playing back keystrokes when pressing keys

### ISSUE THREAD

**Issue by skorokithakis** [asciinema/asciinema#393]
This is a bit of a weird request, but asciinema would be extremely useful in presentations if it could play back my keystrokes when I actually pressed keys, to make it look like I'm live-typing.

Ie it would record when I pressed keys during the recording, and advance the playback from keystroke to keystroke when I pressed any key on the keyboard.

Is this possible to do with the current format/code? If not, what would I need to change to implement this? Any pointers would be appreciated.

**Comment by skorokithakis** [comment]
I have hacked together an implementation of this here:

https://github.com/asciinema/asciinema/compare/develop...skorokithakis:develop

Would anyone be interested in it? It works quite well, though it might need some more features before being releasable, but I can work on it some more if there's interest.

**Comment by ahillio** [comment]
Oh that's exciting.  I look forward to trying this out :)

**Comment by skorokithakis** [comment]
It works rather well, unfortunately it has some disadvantages for presentations, eg if you're writing code you can't switch to another window and run it, as it's all a recording, and you can't pause and resume, or easily edit the commands.

I'm looking into using the methods used by asciinema to create a player that will read a list of commands from a file and type them into a terminal as you type, with options to take over, skip forward/back, see the next commands, etc.

I might post here if there's interest, though it would probably be a separate tool so there's not much sense spamming this issue with that.

**Comment by ahillio** [comment]
Could pause/resume be added back with the functionality you've demonstrated in this patch?

My zsh config has vi-mode and it'd be awesome for a recording to show the keys that are pressed in vi-mode.

I just tried your patch by cloning your repo with the `Implement wait-for-keys` commit and then from inside that directory using `python3 -m asciinema  rec testfile.cast` but I didn't see any indication of the key presses when doing `python3 -m asciinema play testfile.cast`.  Is there a way to toggle the keystroke indication?  Or was I testing it incorrectly?

**Comment by skorokithakis** [comment]
The functionality can certainly be added back, I just removed it to test. The keystrokes don't currently show, this PR is just for only playing the input when pressing keys.

You need to record with `--stdin` for this to work, by the way.

**Comment by ahillio** [comment]
I still plan to try this feature again with your recent suggestion.

I'm also curious to see this possible other project you mentioned and wonder if/how it may be similar/different from https://github.com/sloria/doitlive...?

**Comment by skorokithakis** [comment]
I have tried doitlive and it only worked with the shell and ipython. I used asciinema's terminal code to make It's a Live:

https://gitlab.com/stavros/itsalive

Thanks to asciinema, It's a Live works on every program (nesting two It's a Live sessions possibly doesn't work well though). It also includes a curses-based presenter view, pausing/resuming and other shortcuts.

**Comment by nrktkt** [comment]
I'd love a version of this where you can set pause/breakpoints in the recording. I don't need to show one character of the recording for every key I press, just to automatically pause the playback at specified points and resume on some command (keypress, press play, whatever)

**Comment by skorokithakis** [comment]
@nrktkt It's a Live can already do that.

**Comment by nrktkt** [comment]
@skorokithakis thanks for that realtime response
It's a Live requires you to actually run the commands in the terminal though right? ie. you couldn't playback in the browser

**Comment by skorokithakis** [comment]
@nrktkt Ah, yes, it does need the terminal, correct. You want playback to keep playing on its own until you pause? It can't do that, I'm afraid... I thought you meant the opposite, i.e. type out the entire command with one key press.

**Comment by nrktkt** [comment]
I'd want something halfway between asciinema and It's a Live. So both the input and output are pre-recorded (like asciinema), but with the ability to pause before each command (like It's a Live). 
So if I were to present, I wouldn't need to use my computer to do the presentation

**Comment by skorokithakis** [comment]
Hmm, I think you may be able to fairly easily hack Asciinema to pause before the start of each line of input and wait for a keypress.

**Comment by nrktkt** [comment]
I'd need some pointers on that. Would I be editing asciinema's source or doing something with my terminal recording or?
