### ISSUE TITLE
Certificate validation error when uploading using python3 on macOS 10.15

### ISSUE THREAD

**Issue by bahamat** [asciinema/asciinema#396]
Note: This is done with the system python.

Installed with this command:

    sudo -H pip3 install asciinema

Then made a recording and tried to upload

```
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
asciinema: upload failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
asciinema: retry later by running: asciinema upload /var/folders/rn/rd89mntn58l5tldhb6kgwpzm0000gn/T/tmpft2e6hsg-ascii.cast
```

At the very least, the documentation could be improved to avoid this situation.

**Comment by bahamat** [comment]
It's also worth noting that I have my own version of python installed in a different path that's not the system python and I didn't have an issue there.

**Comment by sickill** [comment]
This looks related to the certificate problem discussed in #235
