### ISSUE TITLE
Vim colors rendered incorrectly with TERM=xterm-kitty

### ISSUE THREAD

**Issue by rnevius** [asciinema/asciinema#408]
As above. Colors render correctly when manually setting `TERM=xterm-256color`, but incorrectly with `TERM=xterm-kitty`. 

[Kitty](https://sw.kovidgoyal.net/kitty/index.html) is a popular terminal emulator.

**Comment by rnevius** [comment]
Closing, as this issue is with the web player.

**Comment by sbeckeriv** [comment]
@rnevius how did you get it to run at all on kitty with `TERM=xterm-kitty`? I came here to open an issue.  using `TERM=xterm-256color` does allow me to run it in kitty. I didnt test any colours yet. 

kitty  0.17
asciinema 2.0.2 

 i get
```
✦ ❯ asciinema rec
asciinema: recording asciicast to /tmp/tmp0w9854hp-ascii.cast
asciinema: press <ctrl-d> or type "exit" when you're done
tput: unknown terminal "xterm-kitty"
Traceback (most recent call last):
  File "/usr/bin/asciinema", line 11, in <module>
    load_entry_point('asciinema==2.0.2', 'console_scripts', 'asciinema')()
  File "/usr/lib/python3/dist-packages/asciinema/__main__.py", line 131, in main
    code = command.execute()
  File "/usr/lib/python3/dist-packages/asciinema/commands/record.py", line 69, in execute
    asciinema.record_asciicast(
  File "/usr/lib/python3/dist-packages/asciinema/__init__.py", line 33, in record_asciicast
    w, h = term.get_size()
  File "/usr/lib/python3/dist-packages/asciinema/term.py", line 35, in get_size
    int(subprocess.check_output(['tput', 'cols'])),
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tput', 'cols']' returned non-zero exit status 3.
```

**Comment by rnevius** [comment]
@sbeckeriv  Have you set up terminfo for Kitty? What is the output of `echo $TERMINFO`?

**Comment by sbeckeriv** [comment]
@rnevius I have not! it is blank. I will look in to that. Thanks.

**Comment by sickill** [comment]
asciinema 2.1 removed dependency on `tput` (ncurses) which should solve the above crash.

**Comment by sickill** [comment]
Are you able to show the screenshots of the correct and incorrect vim colors you observe when recording with asciinema?

**Comment by EgZvor** [comment]
Here's an example cast with wrong colors in Vim

https://asciinema.org/a/580734

**Comment by EgZvor** [comment]
@sickill please, take a look at the above cast
