### ISSUE TITLE
Double free

### ISSUE THREAD

**Issue by NorfairKing** [asciinema/asciinema#411]
I'm getting this error while running `asciinema` in a nix build:

```
efree(): double free detected in tcache 2
```

To reproduce, check this out:

https://github.com/NorfairKing/smos/commit/3badab7a55eaf8799445956682b32e445c95f097

Then run 

```
nix-build nix/pkgs.nix -A smosCasts
```

I'm not sure how/why this would happen because this project looks to be written in Python, which I thought was memory-safe...

**Comment by NorfairKing** [comment]
I managed to reproduce this problem without nix _sometimes_ but I also noticed that this problem doesn't occur when I run the nix build locally (a machine with a screen) but it _does_ occur when I run the nix build remotely (on a machine without a screen).

**Comment by sickill** [comment]
I haven't heard about this problem on other distros, it seems to me like this is nix-specific.

Were you able to pinpoint the problem? I'm afraid my nix skills are close to zero.

**Comment by NorfairKing** [comment]
It's definitely not a nix-specific problem because the problem occurs without nix as well.
I ended up just not using `asciinema rec` but generaiting the casts myself.
