### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by leosaturnin** [asciinema/asciinema#415]
Hello, can someone help me to fix this error?

I tried to run python manage.py migrate and I got the below error.
I'm getting the same error when I used visual studio code to run as well as Atom.

" BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
TypeError: resolve() got an unexpected keyword argument 'strict'  "

**Comment by sickill** [comment]
Is this problem related to asciinema?
