### ISSUE TITLE
[bug] asciinema rec fails in one virtual env and succeeds in other (not a package issue)

### ISSUE THREAD

**Issue by kunzaatko** [asciinema/asciinema#428]
[![asciicast](https://asciinema.org/a/iIyQH7HyEk0pXx2CsPJFOsYWy.svg)](https://asciinema.org/a/iIyQH7HyEk0pXx2CsPJFOsYWy)

The cast shows it all. `asciinema rec` works only after changing the `conda` virtual environment (the specific environment I change it to does not matter). The error is not due to a missing or broken package, but due to an unknown term (which is weird).

Terminals tried:
1) `st-256color`
2) `alacritty`
3) `xterm`

All of them with the exact same outcome (except the change in name in the first non-green line).

**Comment by sickill** [comment]
This has been fixed in v2.1.
