### ISSUE TITLE
Package for Ubuntu

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#43]

**Comment by sickill** [comment]
Hey. I just released 1.0.0 :)

The repo was renamed back to `asciinema`, sorry about that.

All the dependencies are now vendored, so to build asciinema now you only need the source code. Thus `make deps` was removed because it's no longer needed.

Other than these two, nothing changed with regard to building.

/cc @zanchey

**Comment by zanchey** [comment]
Debian policy strongly discourages the shipping of embedded copies of libraries ([4.13 Convenience copies of code](https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles)) so I suspect the official pacakges will try and pull it out, but for a PPA I think it's fine.

New packages built and uploaded, although I haven't been able to test them on all distribution.

**Comment by sickill** [comment]
I get it. Ok, I think having up-to-date ppa is just enough. Thanks!

**Comment by zanchey** [comment]
Yep, works for me :-)

**Comment by mcuelenaere** [comment]
Did you check https://github.com/jordansissel/fpm?

**Comment by zanchey** [comment]
I haven't tried that specifically, although my experience with "universal packaging" tools has been disappointing.

**Comment by sickill** [comment]
@zanchey hey! I just released 1.1.1 ;)

**Comment by zanchey** [comment]
I've uploaded new packages for supported series.

**Comment by zanchey** [comment]
Is there a mailing list or some way of subscribing to release updates?

**Comment by sickill** [comment]
Awesome, thanks!

There's no mailing list at the moment. I was thinking recently about the best way of notifying users, and more importantly, package maintainers about new releases. Mailing list sounds ok. What alternatives do we have?

**Comment by jakubjedelsky** [comment]
@zanchey if you don't want to watch whole project, you can use github's atom (https://github.com/asciinema/asciinema/releases.atom) in your favorite reader or third-party project like https://sibbell.com/about/

**Comment by sickill** [comment]
@jakubjedelsky that's nice. I didn't know about releases.atom

**Comment by sickill** [comment]
Closing this one, will reopen if needed.

**Comment by godmar** [comment]
> Closing this one, will reopen if needed.

It looks like the current debian is 2.4.0, which is two years old.
I'd like to try 3.1.0, but would prefer not to download a binary from github.
Any chance of getting the Debian package updated?

**Comment by ku1ik** [comment]
@godmar It's up to Debian package maintainer(s), I'm not doing any packaging myself. If you'd like to help then maybe you could reach out to them and ask?
