### ISSUE TITLE
Invalid or revoked install ID

### ISSUE THREAD

**Issue by p16andr** [asciinema/asciinema#431]
@sickill @abaykan
How to remove ~/.asciinema/install-id (or ~/.config/asciinema/install-id)

**Comment by p16andr** [comment]
I have asciinema 2.0.2 version

**Comment by p16andr** [comment]
@sickill @abaykan
When i go to remove the file  rm ~/.asciinema/install-id or rm ~/.config/asciinema/install-id  i get an error "no such file or directory"  Why??  Do you know something??

**Comment by sickill** [comment]
Dup of #431
