### ISSUE TITLE
record comments & code from shell scripts in addition to their output

### ISSUE THREAD

**Issue by zechris** [asciinema/asciinema#440]
I thought you might be interested in an [asciinema-rec_script](https://github.com/zechris/asciinema-rec_script) tool that I've created to augment recordings of shell scripts recorded with `asciinema rec --command` with all their comments and code.

So given an ordinary executable bash script like this:
```bash
#!/usr/bin/env bash
## Date maths

# The `date` command can be used to retrieve the:
#  * *day of the week* using the `%l` option
day_of_the_week=$(date +%l)

#  * *hour of the day* using the `%u` option
hour=$(date +%u)


# Now, can you guess what we're going to do with those two numbers?
# 🤔...
sleep 3

# We're going to add them together!
echo $((day_of_the_week + hour))
```

Instead of creating a recording like this with [asciinema rec --command](https://github.com/asciinema/asciinema#rec-filename):
<img width="808" alt="Screen Shot 2021-10-17 at 19 49 14" src="https://user-images.githubusercontent.com/49626717/137619503-05ec8492-f2df-4bc3-a410-ad3300223b8f.png">

[asciinema-rec_script](https://github.com/zechris/asciinema-rec_script#example-usages) can be used to create a recording like this:
[![asciicast](https://user-images.githubusercontent.com/49626717/137620872-d49009a9-0d44-4d7d-a6a6-9dd49a82c8f5.png)](https://asciinema.org/a/pSQTIOh50qKqvU5BFE7tAB5gx)

**Comment by ahillio** [comment]
That's cool! Thanks for sharing :)

**Comment by zechris** [comment]
Thanks @ahillio - I was wondering if _anyone_ in here would notice.
BTW here's a recording that simuates more realistic "typing"....
![updated screencast](https://raw.githubusercontent.com/zechris/asciinema-rec_script/main/screencasts/demo-date_maths.gif)

(Its been converted to a gif with [asciicast2gif](https://github.com/asciinema/asciicast2gif))

I'm hoping to one day provide the production of these as a Github Action, then the screencasts could be generated automatically (by github) in any repo. :)

**Comment by zechris** [comment]
@sickill - https://discourse.asciinema.org/t/is-it-possible-to-script-asciinema/416/8?u=zechris
