### ISSUE TITLE
post process for remove or mark off some data

### ISSUE THREAD

**Issue by dlintw** [asciinema/asciinema#45]
Is it possible?
I want to trim the long record to shorter.

Or, modify some word in record screen. (eg. password or personal information)

**Comment by IvanMalison** [comment]
@sickill is there any word on the editing feature that you mentioned?

**Comment by sickill** [comment]
@IvanMalison you can edit the .json file that is produced by the `asciinema rec out.json` command. Take a look at the last question in FAQ: https://asciinema.org/docs/faq

**Comment by sickill** [comment]
A note on reducing idle time: you can use `asciinema rec --max-wait=2` to compress all pauses (which are longer than 2 seconds) to exactly 2 seconds.

**Comment by IvanMalison** [comment]
@sickill Yeah I took a look at doing that but the format seemed a bit unwieldy.

**Comment by sickill** [comment]
@IvanMalison stdout contains raw text printed to the terminal, including all escape/control sequences. We haven't invented anything on our own. I understand that it's not as easy to understand/edit as it would be if this was converted to a more "visual" representation, however I don't plan to change the format of the "raw material".

You can look at @micahcowan's [teseq](https://www.gnu.org/software/teseq/), which is one approach of this problem.
