### ISSUE TITLE
Save data to files while recording in real time

### ISSUE THREAD

**Issue by cronfy** [asciinema/asciinema#46]
If one wants to record a really large screencast (kernel build, cluster deploy or just a terminal session of several days long), it would  require alot of memory. There is also a risk of that asciinema process can be killed, and in this case even if it catched anything, data wil be lost.

To solve this, asciinema can save data into files in real time. Then it would be possible to recover aborted screencasts and record really long sessions. It also partially solves #21.

**Comment by cyc115** [comment]
This is a long dead thread, but I for one would like to have the ability to recover accidentally closed sessions.
