### ISSUE TITLE
Account recover (email no longer available!)

### ISSUE THREAD

**Issue by vsoch** [asciinema/asciinema#460]
Hi Marcin! I'm user https://asciinema.org/~vs on asciinema.org, and I left Stanford at the beginning of 2021 and no longer have my vsochat [at] stanford email. I can prove that I own the account because my computer is still logged in and I just uploaded https://asciinema.org/a/FMQaYHfyBFwLtpKFl1vLYZLWz (and then realized in terror I can't login to customize because my stanford email doesn't exist!) Would it be possible to update my email so I don't lose my account? I'm happy to upload any niche assinema to prove that I own the original auth. Thank you!

**Comment by vsoch** [comment]
Hi! Me again. I am again having weirdness with my account - I was able to upload OK https://asciinema.org/a/pF0bMz1uMO8ToqKRcpi7vJ0T3 but since the browser logged me out, I can't edit/ change the status. The click of the link to login seems to not be sending any email, so either my email was never changed from the old stanford one, or there is a bug / delay of some kind. Please help! I don't want to lose my account!

**Comment by sickill** [comment]
There was an issue with email delivery in last few days which I hopefully solved by now. Please try again. Let me know if you're good.
