### ISSUE TITLE
[Question] Is it possible to do the same as asciinema but for the browser?

### ISSUE THREAD

**Issue by simkimsia** [asciinema/asciinema#461]
Sorry i cannot find a Discussions so I create an issue marked as Question.

Is it possible to record browser interactions and have it play back and have the recording allow copy-paste like the way asciinema does it?

I understand asciinema targets the terminal, i'm asking as a general question of the feasibility of the same benefits but for the browser

**Comment by sickill** [comment]
I'm sure someone already did that :)

**Comment by bkil** [comment]
That would be great, but security policies prohibit from recording the screen like that. Embedding a browser engine for just that and printing the rendered form would work, but would be again big.

Periodically snapshotting the DOM to maintain it being easy to copy & paste or read aloud by a screen reader seems like an open problem.

It would be also great to store the DOM in a minimized or non-lossless compacted form (or only the diff), similar to patented technology that crawlers are doing under the hood.

But surely all of this is out of scope for asciinema - I don't think that there would be any common code between the two.
