### ISSUE TITLE
Windows not supported, right?

### ISSUE THREAD

**Issue by maphew** [asciinema/asciinema#47]
A quick pip install test from the Github repo reveals that asciicinema doesn't work out of the box on Windows, even though it does install an .exe to the Python Scripts folder. On my Win7 machine It fails with `ImportError: No module named termios`.

A little searching reveals there (probably) isn't a  Windows equivalent,
http://stackoverflow.com/questions/933745/what-is-the-windows-equivalent-to-the-capabilities-defined-in-sys-select-h-and-t, and that therefore asciicinema is likely not supposed to work on Windows.

It would be good if the Readme states what operating systems asciicinema is intended for / known to work on.

**Comment by noisy** [comment]
@sickill is it possible to support cygwin?

**Comment by sickill** [comment]
@noisy cygwin doesn't support UNIX-like pseudo-terminal so it's unlikely to make it work on Windows. All UNIX family systems (Linux, *BSD, Mac OS X), have PTYs, but Windows is a completely different OS.

**Comment by masaeedu** [comment]
@sickill What about https://github.com/rprichard/winpty?

**Comment by sickill** [comment]
@masaeedu feel free to experiment with it. I'm fine with someone maintaining a friendly Windows fork of asciinema. However, at this moment I'm interested in merging any Windows specific changes into the main repository. [asciicast format](https://github.com/asciinema/asciinema/blob/master/doc/asciicast-v1.md) is documented, so as long at recording on Windows produces compatible asciicast file, the web player should be able to replay it.

**Comment by sickill** [comment]
@masaeedu There is Windows fork by @mattn - https://github.com/mattn/asciinema/tree/windows

**Comment by sickill** [comment]
I was wrong saying "it will never support Windows" :)
It seems it now installs and works perfectly fine under Win10 (WSL): https://asciinema.org/a/123255

**Comment by amistele** [comment]
March 28 2018, 
I tried a pip install of asciinema on Windows 10, and encountered the termios error. Is this still resolvable, or where do i go to fork a compatible version?

**Comment by mattn** [comment]
@amistele see https://github.com/asciinema/asciinema/issues/150

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/issues/136

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/issues/292

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/pull/152

**Comment by mikemaccana** [comment]
@sickill Windows 10 now has an [official console api](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/), which should make Windows support require far less code. Does that change anything?

**Comment by sickill** [comment]
@mikemaccana thank for bringing this up! I think this could open the way for native Windows support. I just skimmed through the linked article, but it looks promissing 👍

**Comment by Kiedtl** [comment]
@sickill Have you taken a look at winpty? It's README claims to work on Windows XP and later.

**Comment by rollingmoai** [comment]
This port for Windows works great: https://github.com/Watfaq/PowerSession-rs. It would be nice if Asciinema would officially support Windows.
