### ISSUE TITLE
Asciinema hangs when pty is not available

### ISSUE THREAD

**Issue by DavidVentura** [asciinema/asciinema#482]
Hi

I'm running asciinema as a subprocess in CI to record some commands. Something like `subprocess.Popen(['asciinema', ...])`. This works great in any local machine, but hangs in CI, without even spawning the process to record.

I've fixed it by passing a new pty for the process:

```
import pty
master, _ = pty.openpty()
subprocess.Popen(cmd, stdin=master, stdout=master)
```

but I believe asciinema could detect this and automatically spawn a new pty

**Comment by DavidVentura** [comment]
as a note for anyone with similar issues -- you also need to set the size of the pty:
```python
def _make_pty():               
    master, _ = pty.openpty()
    our_winsz = struct.pack("HHHH", 40, 85, 0, 0)
    fcntl.ioctl(master, termios.TIOCSWINSZ, our_winsz)
    return master
```

**Comment by sickill** [comment]
Can you try the latest code from develop branch? There's a chance that recent changes there improved this.

**Comment by sickill** [comment]
Could you test this on the latest v2.2.0?

**Comment by DavidVentura** [comment]
Works great!
