### ISSUE TITLE
Planned release schedule?

### ISSUE THREAD

**Issue by kai-tub** [asciinema/asciinema#486]
Thank you for working on such an interesting project! :heart:
I am wondering if there is any release schedule or project board that indicates what is required for the next release.
If not, and a release is not planned for a long-time, is it possible to draft an alpha release for PyPi?
I am happy to help with this!

The reason is that I would like to publish a package to PyPi that depends on the current asciinema recorder, but cannot publish it, since there is no way to add GitHub dependencies.
The package I am working on is a sphinx extension that embeds the asciinema-recorder/player to make it easy to automate terminal recordings for the documentation.
You can see the preliminary documentation [here](https://docs.kai-tub.tech/sphinx_cli_recorder/intro.html). 

Maybe I will be able to give back to the project by using this extension and Sphinx to write similar documentation to the [configuration](https://docs.kai-tub.tech/sphinx_cli_recorder/05_configuration.html) page for this repository?

Either way, I am well aware that you have zero obligation to release something ahead of schedule or feel pressured to publish an alpha release. 
Feel free to close this issue without any comment if you consider it an inappropriate question :)
I am mainly curious and excited to use and build on top of such an amazing tool.

PS: The code will be published according to GPL once it has been published to PyPi.

**Comment by sickill** [comment]
Hey! I'm glad you find asciinema useful. I don't have a specific schedule, usually I release when I feel it's "ready". I don't plan any new major things for the upcoming release so it's likely that it will go out within next few days.

**Comment by sickill** [comment]
v2.2 has just been released @kai-tub

**Comment by kai-tub** [comment]
Nice!
Thank you! 🎉

**Comment by kai-tub** [comment]
My project has been published to PyPi and I made the library public with the GPL license:
https://github.com/kai-tub/sphinx_cli_recorder
Thanks for giving us asciinema! :+1:
