### ISSUE TITLE
Package for Fedora 

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#50]
Looks like Jakub Jedelsky is already doing some work in that matter: https://bugzilla.redhat.com/show_bug.cgi?id=1034492

**Comment by sickill** [comment]
Hey. I just released 1.0.0 :)

The repo was renamed back to `asciinema`, sorry about that.

All the dependencies are now vendored, so to build asciinema now you only need the source code. Thus `make deps` was removed because it's no longer needed.

Other than these two, nothing changed with regard to building.

/cc @jakubjedelsky

**Comment by jakubjedelsky** [comment]
Hi Marcin,

I'm watching it and I'll start to prepare package asap. Go asciinema will be available for Fedora only - epel hasn't dependencies ready yet.

**Comment by sickill** [comment]
Great, thanks!

**Comment by jakubjedelsky** [comment]
I just took a closer look and have the same problem as in #43  - we have to use libraries from repositories, not to build and deliver duplicated code from package. 
Package for github.com/docopt/docopt-go is not prepared for Fedora yet so I must prepare it first. Because of that it takes a while to prepare correct asciinema package.

**Comment by jakubjedelsky** [comment]
Package for Fedora is prepared, just waiting for dependency docopt-go to be pushed to repositories and I'll push the asciinema itself. The v1.0.0 will go to Fedora 22 (in alpha right now) and rawhide (development) only - in stable repos it will be in 7+ days. Unfortunately there aren't dependencies in EPEL 6 nor 7 repos yet.

For early adopters there is my own copr repo with new version: https://copr.fedoraproject.org/coprs/kubo/asciinema/

I think we can close this issue.

**Comment by sickill** [comment]
:+1:

**Comment by sickill** [comment]
@jakubjedelsky hey! I just released v1.1.1 ;)

**Comment by jakubjedelsky** [comment]
I got it. There is a new dependency (termios) which isn't in Fedora repos yet so I have to push it there first. And it can takes some time. I'll send an update here.

**Comment by jakubjedelsky** [comment]
Asciinema 1.1.1 is available in my copr repository: https://copr.fedoraproject.org/coprs/kubo/asciinema 

For official Fedora repositories I have to get a review for creack/termios package. When this package will be in repositories, I can push new version of asciinema there. Feel free to close this issue, I'm notified by RedHat's bugzilla with every new release.

**Comment by sickill** [comment]
Thanks Jakub!
