### ISSUE TITLE
[Feature Request] --append should work if file is empty of doesn't exist

### ISSUE THREAD

**Issue by hycday** [asciinema/asciinema#507]
Hi all,

It would be really helpful to be able to have asciinema to automatically create a file in a given chmod, if it doesnt exist, so that --append would work, if the file doesnt exist.

Idea would be to run asciinema on startup, or everytime terminal is open, and append the initial file.

Today, if the file doesnt exist, and the command has --append, then it wont work...
So ideally, it would be nice to be able to use --append, and if file doesnt exist, asciinema would create it...

Note: same applies if file exists but is empty, today it doesn't work, but ideally it should work..

**Comment by ku1ik** [comment]
Hey! I double-checked this and in fact `--append` works when file doesn't exist since asciinema 2.2, which was released a month before you filed the issue, so you were probably on 2.1 or earlier version back then.
