### ISSUE TITLE
Consider including more visual examples?

### ISSUE THREAD

**Issue by kai-tub** [asciinema/asciinema#525]
Hey, thank you for working on this project! :+1:
I was wondering if you would consider updating the `asciinema` Python documentation on a stand-alone documentation website.
I am more than happy to help set up a template documentation site and configure anything Sphinx related.
My _ulterior_ motive is that I would be interested in potentially 'upstreaming' some of my _documentation_ to the `asciinema` project:
- https://docs.kai-tub.tech/sphinx_cli_recorder/05_configuration.html (PS I am having issues with changes from my domain provider, if you can't open the page, please ping me)

I am happy to answer any questions/concerns you might have and help you with Sphinx if you haven't used it before. :)

Cheers!

**Comment by sickill** [comment]
Hey. I haven't used Sphinx and I don't have a use case at the moment (or I don't know I have :))
Thanks for the offer but I'll stick to documentation in repo READMEs for now.

**Comment by kai-tub** [comment]
Sure. Thanks for responding! :)
