### ISSUE TITLE
Incorrect rendering of DEC Special Graphics, which is used in ncurses Nethack

### ISSUE THREAD

**Issue by leonyu** [asciinema/asciinema#527]
[DEC Special Graphics](https://en.wikipedia.org/wiki/DEC_Special_Graphics) characters are rendered incorrectly. 

This can be produced by the following oneliner: 
```sh
python3 -c 'for i in range(95, 127): print(f"{i:x} | \x1b(0{chr(i) * 4}\x1b(B | {i:x}")'
```
https://asciinema.org/a/6wW8RLBjuampesVCrbDUEjX62

These characters are used by ncurses Nethack: 

https://asciinema.org/a/LguWxEd8Sju8Hc6lKtpmLlsX4

**Comment by sickill** [comment]
How should it look like?

This is how it looks like for me on Arch Linux / Firefox 106:

![image](https://user-images.githubusercontent.com/17589/200116777-ff2acf6c-fbed-40fa-b1e4-1e585a0334f6.png)

**Comment by leonyu** [comment]
![image](https://user-images.githubusercontent.com/304902/200117021-9dab8f83-5169-46ae-a7de-cb66ced81b66.png)

I am on Windows 10 chrome. 

It looks like Consolas doesn't have those glyphs, so it has to pick another font, in this case Cambria Math

![image](https://user-images.githubusercontent.com/304902/200117444-dc5d1802-f089-40f4-9d11-eebd9000a60c.png)

**Comment by leonyu** [comment]
I don't know if there's a wholistic solution for this. I think VS Code had similar issue and [switched to use canvas for terminal rendering](https://code.visualstudio.com/blogs/2017/10/03/terminal-renderer). I think they use [Xterm.js](https://www.npmjs.com/package/xterm).

**Comment by sickill** [comment]
Yeah, holistic solution is a holy grail :) It's just browsers render text differently, and I'm afraid without switching to canvas + carefully selected set of font faces there will always be something off. There's no plan for canvas impl in short term but in long term we may go there.

**Comment by leonyu** [comment]
It is also possible to detect the rendering size of the characters using Canvas/OffscreenCanvas then make adjustments with rendering accordingly.

**Comment by sickill** [comment]
That's interesting idea 💡
