### ISSUE TITLE
Github hacker ?

### ISSUE THREAD

**Issue by nkakouros** [asciinema/asciinema#529]
Under the wiki, there is a page called Github Hacker (https://github.com/asciinema/asciinema/wiki/GitHub**hacker). What is this about?

**Comment by galoget** [comment]
From what I saw, everyone can collaborate in the Wiki (Add, Edit or Delete content), so that page was created by someone. The repository was not hacked (Just FYI).

**Comment by sickill** [comment]
Hmm, I don't see this page anymore... 🤔

**Comment by galoget** [comment]
Yes, that's because I deleted it, to restore the original structure to the Wiki.

**Comment by sickill** [comment]
Aha, thanks!
