### ISSUE TITLE
upload failed: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR]

### ISSUE THREAD

**Issue by navyad** [asciinema/asciinema#530]
`rec` and `play` commands are working fine.
But upload fails with following error.
```
asciinema: upload failed: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992)>
asciinema: retry later by running: asciinema upload demo.cast
```
Is there issue with ssl library ?

```
❯ python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1q  5 Jul 2022
```

* installed using pip3 using Python 3.11.1
* MacOS Catalina 10.15.4

**Comment by fahuihu** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，谢谢对外经济贸易大学，信息学院，朱文强

**Comment by sickill** [comment]
It's a problem with your Python or OpenSSL installation. There isn't any explicit code in asciinema that deals with TLS.

**Comment by AkechiShiro** [comment]
This issue should be closed, IMHO
