### ISSUE TITLE
latest image broken due to wrong arch binary

### ISSUE THREAD

**Issue by SNB-hz** [asciinema/asciinema#541]
Trying to use the latest image from Github container registry yields the following error:
`exec /usr/local/bin/asciinema: exec format error`

Apparently the image contains a binary compiled for a different architecture.
Affected image sha256: `bc05a57bf4cbd3d6708ed7abdd38b5924cdb6394bb9e6c5a1361ae8d7e409354`

**Comment by sickill** [comment]
What arch are you installing on?

**Comment by SNB-hz** [comment]
x86_64
the same k8s cluster ran the old docker images (`asciinema/asciinema-server:latest
`) for months without issues. Had to clear the docker image cache and therefore switched to the Github container registry images. All other settings apart from image URL remained unchanged

**Comment by sickill** [comment]
Ah, so that's about asciinema-server image, not asciinema (this repo), got it.

**Comment by sickill** [comment]
The asciinema-server one seems to be fine, just tested it on x86_64 box:

```
$ docker run --rm -ti ghcr.io/asciinema/asciinema-server /bin/bash
Unable to find image 'ghcr.io/asciinema/asciinema-server:latest' locally
latest: Pulling from asciinema/asciinema-server
c158987b0551: Pull complete
d19f5f8273fc: Pull complete
648e90b5aaa2: Pull complete
29341731aa8a: Pull complete
3d92658f2790: Pull complete
32d5a33f1d1f: Pull complete
Digest: sha256:0bb5c6507a6857c895ea9aa4784479116c820aff16883b99e0a878e372f7db26
Status: Downloaded newer image for ghcr.io/asciinema/asciinema-server:latest
4df981118135:/opt/app#
```

**Comment by sickill** [comment]
The image for asciinema cli (recorder) is indeed wrong arch:

```
$ docker run --rm -ti ghcr.io/asciinema/asciinema
Unable to find image 'ghcr.io/asciinema/asciinema:latest' locally
latest: Pulling from asciinema/asciinema
d4ba87bb7858: Pull complete
b4639dc8989d: Pull complete
4f4dc9bf5393: Pull complete
746198c1250a: Pull complete
1ca33713fa09: Pull complete
26d42e37ecee: Pull complete
5efbb974746e: Pull complete
b1f97fcad540: Pull complete
Digest: sha256:bc05a57bf4cbd3d6708ed7abdd38b5924cdb6394bb9e6c5a1361ae8d7e409354
Status: Downloaded newer image for ghcr.io/asciinema/asciinema:latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/local/bin/asciinema: exec format error
```

**Comment by sickill** [comment]
Just fixed the above problem.

If you're looking for asciinema server image then make sure you use `ghcr.io/asciinema/asciinema-server` image, not `ghcr.io/asciinema/asciinema`.
