### ISSUE TITLE
The record format is not json

### ISSUE THREAD

**Issue by alptekinynk** [asciinema/asciinema#544]
I've seen that older versions of Asciinema can record in json format.

`asciinema rec rec.json`

But ubuntu 22.04 I'm using and I can't record in json format in asciinema version 2.2.0. The above code works, but the content of the record file is exactly the same as the files with .cast extension.
Is this a completely removed feature for version 2.2.0?

**Comment by sickill** [comment]
Old json format was dropped in recorder 5 years ago, in version 2.0. See https://blog.asciinema.org/post/two-point-o/
