### ISSUE TITLE
Website CSS: adapt to @prefers-color-scheme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [asciinema/asciinema#546]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by vitaly-zdanevich** [comment]
But this page is white 
![image](https://user-images.githubusercontent.com/3514015/233710994-c91dae5a-d8ac-4365-a1e1-7dbb0919efe2.png)

**Comment by sickill** [comment]
This repo is for asciinema cli, not for the website. Also, you haven't described your issue, you just pasted some link.

**Comment by vitaly-zdanevich** [comment]
What is the repo for the website?
