### ISSUE TITLE
Cannot playback videos in 2.2.0, 2.3.0 and git HEAD versions of CLI

### ISSUE THREAD

**Issue by msva** [asciinema/asciinema#563]
Hi there!
I'm facing strange issue: when I trying to play recorded asciinemas with CLI, I'm getting strange error:
```
asciinema: playback failed: <link rel="alternate" type="application/x-asciicast" href="..."> not found in fetched HTML document
```

But if I add ".json" at the end - it plas fine (but nobody pastes ascinema links with ".json" at the end, on the internets :shrug:)

Here is the asciinema with the demonstrations:

[![demo](https://asciinema.org/a/eYQ7ckAYCOiyyBPJYYabQgmYp.svg)](https://asciinema.org/a/eYQ7ckAYCOiyyBPJYYabQgmYp?autoplay=1)

Actually, maybe this is server issue at all?

**Comment by sickill** [comment]
Thanks for reporting. Turns out this is server issue. This part https://github.com/asciinema/asciinema-server/blob/develop/lib/asciinema_web/templates/recording/meta.show.html.eex is not included in response HTML for some reason. I'll debug this and let you know once it's fixed.

**Comment by sickill** [comment]
Should work find now with 2.3.0.

**Comment by msva** [comment]
Yeah thanks a lot
