### ISSUE TITLE
How can I export command output to file.md or even file.svg?

### ISSUE THREAD

**Issue by DragonSerW** [asciinema/asciinema#573]
Hello guys! )
I use `figlet` to export text as file.nfo:

```
[dragonserw@fedora ~]$ figlet DragonSerW | tee -a ./DragonSerW.nfo
 ____                              ____          __        __
|  _ \ _ __ __ _  __ _  ___  _ __ / ___|  ___ _ _\ \      / /
| | | | '__/ _` |/ _` |/ _ \| '_ \\___ \ / _ \ '__\ \ /\ / / 
| |_| | | | (_| | (_| | (_) | | | |___) |  __/ |   \ V  V /  
|____/|_|  \__,_|\__, |\___/|_| |_|____/ \___|_|    \_/\_/   
                 |___/                                       
[dragonserw@fedora ~]$ 
```

My question is:
I need that formatted text as output file.svg or file.pdf.
Can asciinema do such thing? ;-))
For now I save bash output to file.md and then I print it with Document Viewer (to .pdf and to .svg).

**Comment by ku1ik** [comment]
Hey! asciinema doesn't produce `.md` nor `.pdf` files as it's primary use case is animated output. Checkout pandoc, there may be simple way to convert any text file (or output) into PDF with it.
