### ISSUE TITLE
Hanging after a +2 hours recording

### ISSUE THREAD

**Issue by dannywillems** [asciinema/asciinema#595]
**Describe the bug**

I tried to record a (time) long execution trace, for around 2hours. When trying to exit with CTRL-D or exit, it hangs. It's been +40min it is hanging on the exit command, and the process doesn't respond.

**To Reproduce**
Record + 2h process

**Expected behavior**

Get the .cast file when exiting.

**Versions:**
 - OS: [Ubuntu 22.04]
 - asciinema cli: [e.g. 2.4.0]

**Additional context**
N/A

**Comment by ku1ik** [comment]
Are you able to reproduce the problem with a shorter session?

Any commands in particular you used in that session?

asciinema records to a file in real-time, so the file should be there, even if ending the recording sessions couldn't happen (for some reason).

**Comment by dannywillems** [comment]
I wasn't able to reproduce the problem with a shorter session.
The commands were mostly recording `git`, `cargo` and relatively simple bash scripts.
The recording was taking a long time because of the recorded command.

I didn't go deeper as I only needed asciinema once, and I ended up using a screen recording software.

**Comment by ku1ik** [comment]
Ok. I'm going to close this then.
