### ISSUE TITLE
Doesn’t build in MacOS?

### ISSUE THREAD

**Issue by larrypl** [asciinema/asciinema#597]
**Describe the bug**
`cargo build` on MacOS results in error message about execvpe missing

**To Reproduce**
1. clone, switch to develop branch
2. `cargo build`
3. See error

**Expected behavior**
Build asciinema

**Versions:**
 - OS: Darwin XXX 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
 - asciinema cli: 3.0

**Additional context**
Error message:
```
error[E0425]: cannot find function `execvpe` in module `unistd`
   --> src/pty.rs:228:13
    |
228 |       unistd::execvpe(&args[0], &args, env)?;
    |               ^^^^^^^ help: a function with a similar name exists: `execve`
    |
   ::: /Users/larry/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/unistd.rs:845:1
    |
845 | / pub fn execve<SA: AsRef<CStr>, SE: AsRef<CStr>>(
846 | |     path: &CStr,
847 | |     args: &[SA],
848 | |     env: &[SE],
849 | | ) -> Result<Infallible> {
    | |_______________________- similarly named function `execve` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `asciinema` (bin "asciinema") due to previous error
```

**Comment by ku1ik** [comment]
Thanks for testing this! This should be easy to solve.

**Comment by ku1ik** [comment]
This build problem is now fixed by https://github.com/asciinema/asciinema/commit/b96e95bec8296ee25c3e4316095c9f601ea21825, I successfully compiled it.

**Comment by ku1ik** [comment]
There's another problem to solve on macOS: https://github.com/asciinema/asciinema/issues/598

**Comment by larrypl** [comment]
Yes, it builds now - thanks!
