### ISSUE TITLE
Error: missing field `play` when attempting to run any command

### ISSUE THREAD

**Issue by kitesi** [asciinema/asciinema#603]
**Describe the bug**

When I try to run any command (rec, play, cat, upload) with a file, it gives me the error: 

"Error: missing field \`play\` "

with no further information. 

**To Reproduce**
1. Run `asciinema rec demo.cast`, `asciinema cat demo.cast`, `asciinema play demo.cast`, ...
2. See error

**Expected behavior**
Work as shown in demo.

**Versions:**
 - OS: Linux Mint, 5.15.0.-91-generic
 - uname -a: Linux seven-Latitude-5300 5.15.0-91-generic (#) 101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - asciinema cli: 3.0.0-alpha.7

**Additional context**
I haven gotten these errors on a fresh installation with both `cargo build --git ...` and building it by cloning directly.

**Comment by ku1ik** [comment]
Thanks, I know what's up, will push a fix shortly.

**Comment by ku1ik** [comment]
Should work now @kitesi.
