### ISSUE TITLE
Generate man page

### ISSUE THREAD

**Issue by alerque** [asciinema/asciinema#627]
I just started playing around with [updating the Arch Linux packaging](https://gitlab.archlinux.org/archlinux/packaging/packages/asciinema/-/merge_requests/1) in preparation for the v3 release. It looks like one regression over the Python package is that there is no man page.

Since the Rust rewrite is using Clap it should be pretty easy to generate a correct and in sync man page from the CLI interface setup using clap_mangen. There is not reason this *has to* make the final v3 cut, but I figured whether early or late a tracking issue is warranted so downstream packages know if it is or isn't available and how it is generated.

**Comment by ku1ik** [comment]
Hey! Awesome that you're already looking into it :heart_eyes: 

Both man page generation and shell completions are on my list of things to do before cutting the final v3, hope to get to this very soon.

Not sure whether build-time or run-time generation of a man page would be better here, but I think the build-time generation as described in [clap_mangen's example](https://github.com/clap-rs/clap/blob/master/clap_mangen/README.md should be good enough. This would produce both the binary and the man page, putting them both in the same out dir, easy for packaging. What do you think?

**Comment by alerque** [comment]
Personally (as a distro packager) I *much* prefer build-time generation for these sort of assets. The argument in favor of run-time is for folks who `cargo install` on whatever in their user space rather than installing system packages, but my experience is those folks are much less likely to expect or use a man page in the first place.

And yes having the man page generated to the Cargo OUT_DIR is fine.

**Comment by ku1ik** [comment]
> but my experience is those folks are much less likely to expect or use a man page in the first place.

This is my experience as well.

**Comment by ku1ik** [comment]
You can now generate man page during build by setting `ASCIINEMA_GEN_DIR` env var - the file will be saved as `$ASCIINEMA_GEN_DIR/man/asciinema.1`.

**Comment by xfgusta** [comment]
I noticed that the man page seems a bit empty compared to the old one. There are mentions of other man pages for the subcommands, but these man pages are not generated. I'm not sure if this is intended.

```console
$ man asciinema
[...]
SUBCOMMANDS
       asciinema-rec(1)
              Record a terminal session

       asciinema-play(1)
              Replay a terminal session
[...]
```

```console
$ man asciinema-rec
No manual entry for asciinema-rec
```
