### ISSUE TITLE
unable to upload multiple recordings at once

### ISSUE THREAD

**Issue by evakhoni** [asciinema/asciinema#629]
**Describe the bug**
trying to upload multiple recordings at once, 
the software recognizes the additional files as unrecognized arguments

**To Reproduce**
❯ asciinema upload *.cast
usage: asciinema [-h] [--version] {rec,play,cat,upload,auth} ...
asciinema: error: unrecognized arguments: details.cast main.cast status.cast

**Expected behavior**
upload successful
or at least a reasonable message

**Versions:**
 - Fedora release 39
 - asciinema 2.3.0

**Comment by moritzdietz** [comment]
May I suggest:
```bash
for recording in  details.cast main.cast status.cast; do asciinema upload "$recording"; done
```

**Comment by ku1ik** [comment]
That's what I'd suggest as well. Thanks @moritzdietz.

**Comment by evakhoni** [comment]
yeah there are definitely workarounds available for this one. just the current situation of it recognizing it as `unrecognized arguments` seems buggy to my eyes

**Comment by ku1ik** [comment]
```
> asciinema upload --help
Upload a recording to an asciinema server

Usage: asciinema upload [OPTIONS] <FILENAME>

Arguments:
  <FILENAME>  Filename/path of asciicast to upload

Options:
      --server-url <SERVER_URL>  asciinema server URL
  -q, --quiet                    Quiet mode, i.e. suppress diagnostic messages
  -h, --help                     Print help

```

The help message clearly states it accepts 1 filename so it works as expected.
