### ISSUE TITLE
In Fedora 40 in gnome-terminal asciinema 3 beta don't record colors

### ISSUE THREAD

**Issue by yodatak** [asciinema/asciinema#630]
-----

**Describe the bug**
When i try to record my terminal i use v3.0.0-rc.2

`asciinema rec -t less /home/yodatak/Documents/asciinema/less.cast`

the recording
```
{"version":2,"width":238,"height":49,"timestamp":1715682676,"title":"less","env":{"SHELL":"/bin/bash","TERM":"xterm-256color"},"theme":{"fg":"#ffffff","bg":"#1e1e1e","palette":"#171421:#c01c28:#26a269:#a2734c:#12488b:#a347ba:#2aa1b3:#d0cfcc:#5e5c64:#f66151:#33da7a:#e9ad0c:#2a7bde:#c061cb:#33c7de:#ffffff"}}
[0.045786, "o", "\u001b]0;yodatak@fedora:~\u0007"]
[0.046166, "o", "\u001b]7;file://fedora/home/yodatak\u001b\\"]
[0.046375, "o", "\u001b[?2004h"]
[0.046425, "o", "\u001b[32myodatak@fedora\u001b[0m:\u001b[32m~\u001b[0m$\u001b[0m "]
```

and i got no colors insted of 

<pre><font color="#26A269">yanis@fedora</font>:<font color="#26A269">~</font>$ ls
<font color="#12488B"><b>Bureau</b></font>  <font color="#12488B"><b>Documents</b></font>  <font color="#12488B"><b>Images</b></font>  <font color="#12488B"><b>Modèles</b></font>  monfichiermagique  <font color="#12488B"><b>Musique</b></font>  <font color="#12488B"><b>Public</b></font>  <font color="#12488B"><b>Téléchargements</b></font>  <font color="#12488B"><b>Vidéos</b></font>  zsh</pre>

but when i play asciinema play less5.cast i got colors

**To Reproduce**
1. install ascinema on default fedora workstation 40
2. put in player
3. white only text

**Expected behavior**
Show the colors

**Additional context**
Maybe its because it dont detect the colors and only a white theme ( but i don't use it  weird)
Maybe some gnome issue i don't understand

**Comment by ku1ik** [comment]
So you're missing the colors when replaying with the js player on your html page?

**Comment by yodatak** [comment]
Yes I'm missing colors and the file don't show blue color of my default prompt and I canot understand why it don't record my prompts colors

**Comment by ku1ik** [comment]
Do you use the latest version of the player? (don't forget about updating the CSS file too)

Support for original terminal colors was added in one of the recent versions of the player.
