### ISSUE TITLE
cargo instuctions not working

### ISSUE THREAD

**Issue by kb3ien** [asciinema/asciinema#635]
cargo install --git https://github.com/asciinema/asciinema

results in 

    Updating git repository `https://github.com/asciinema/asciinema`
error: failed to find branch `master`

Caused by:
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)

**Comment by ku1ik** [comment]
What version of cargo do you have?

**Comment by kb3ien** [comment]
cargo 1.46.0


ii  cargo                                         0.47.0-3+b1                        amd64        Rust package manager

**Comment by ku1ik** [comment]
You need at least Rust 1.70 (both Rust compiler and Cargo), as mentioned in the Building section of the README.
