### ISSUE TITLE
Account recovery (email no longer available)

### ISSUE THREAD

**Issue by pjg11** [asciinema/asciinema#647]
Hello! I'm [pjg1](https://asciinema.org/~pjg1) on asciinema. I uploaded a recording by mistake (this was back when `asciinema rec` uploaded directly before asking), and then realized I couldn't log in to the website because I think the email I used doesn't exist anymore (the one-time link doesn't go to any of my existing emails).

Is there a way to change the email and access the account? I can upload recordings, but none of them show up as public recordings, so let me know if there's any other proof I need to submit.

**Comment by ku1ik** [comment]
Drop me an email (check here) and I'll try to help you.

**Comment by pjg11** [comment]
Solved, thanks!
