### ISSUE TITLE
impossible to install on Debian 12 

### ISSUE THREAD

**Issue by omorrigancloud** [asciinema/asciinema#649]
i was following the documentation to install asciinema on a Debian 12 VM to record terminal sessions to my asciinema account, but when i tried to give the command the  package manager failed to find the .deb fileintode pkg repo. 
It is important to note that it was a new installation which did not undergo any modifications to the repositories.

**Comment by ku1ik** [comment]
This is a Debian packaging problem so I recommend reaching out to the current maintainer of asciinema package in Debian.
