### ISSUE TITLE
Feature request: Redact specified strings / regexes

### ISSUE THREAD

**Issue by 5HT2** [asciinema/asciinema#657]
**Describe the feature**

I would appreciate the ability to redact specific strings or regexes from recordings & streams.

I did consider "just pipe your commands through a filter", but I would like to present the following points:
1. ssh & similar make it incredibly annoying and difficult to share recordings of a session where you can't as easily pipe the entire session through a filter
2. high-throughput recordings make it easy to miss data / env variables / keys / similar
3. what needs redacted is an IP / hostname / something that is part of a machine's shell prompt a.k.a. PS1
4. what if I would like to replace it with auitable placeholder text?

I understand that this entirely free software with hosting that is paid for out of pocket - the ability to redact specific information in-real-time is important to me, however much I would like to use this tool otherwise.

I would also be just as happy to open a pull request if this is a feature that you are willing to consider.

**Behavior goals**

The usage flags could include:
- `--redact-mode`: [none (default) | string (exact string match) | regex | config]
- `--redact-char`: `char` to replace redacted content with.
  - Default to a single space, or maybe `•` / `*`
  - Making the default a single space means it's easy to change it to literally nothing, for a use case where the length of the redacted content is already a giveaway.
- For more complicated replacement configurations it would make more sense to take a key:value config file, though I suppose it could just be done by taking each addition duplicate parameter as an additional redaction key

**Comment by ku1ik** [comment]
Have you tried using `awk`, `sed` or similar tool to replace occurrences of sensitive information in existing `.cast` files? The recordings encode the terminal output in plain text, which is easily greppable, so it should be pretty easy to setup an `awk` pipeline/script/alias to do that automatically after every recording session.

**Comment by 5HT2** [comment]
Oh I did not realize that you could just modify the cast files after the fact. That's a fine solution then, thank you!
