### ISSUE TITLE
upload recording as private

### ISSUE THREAD

**Issue by omaraboumrad** [asciinema/asciinema#66]
Kindly add a new feature to asciinema.org allowing users to change a recording's visibility.

**Options**: Public/Private

**Example setting through terminal**:

~ Asciicast recording finished.
~ Do you want to upload it? [Y/n] Y
~ Do you want to make it private? Y

Thank you!

**Comment by KenjiHollis** [comment]
:+1:

**Comment by sickill** [comment]
Good news! Private asciicasts just landed for everyone: http://blog.asciinema.org/post/private/

**Comment by KenjiHollis** [comment]
AWESOME!!!!!!!  Thank you so much for doing this!!
