### ISSUE TITLE
change to config format

### ISSUE THREAD

**Issue by zanchey** [asciinema/asciinema#76]
I have a config file which I'm pretty sure is from 0.9.7. When I run 0.9.9 I get this error:

```
invalid section: section "user"
```

My old config looks like this:

```
[user]
token = <my token>

[api]

```

Blowing it away allows asciinema to start. My new config is:

```
[api]
token = <my token>
```

I couldn't see anything about this in the release notes.

**Comment by sickill** [comment]
This has been fixed in ce34fed.
