### ISSUE TITLE
`--yes` shouldn’t need a value

### ISSUE THREAD

**Issue by vitorgalvao** [asciinema/asciinema#84]
Applying `-y` or `--yes` with `asciinema rec` should activate the option, while putting nothing should deactivate it. Supplying a `--yes` flag when you want something makes more sense than saying “yes false” or “yes true”.

On asciinema 1.0.0.rc1.

**Comment by sickill** [comment]
Thanks for feedback. This has been improved in master: https://github.com/asciinema/asciinema/blob/master/main.go#L20-L40

**Comment by vitorgalvao** [comment]
Yep, was getting ready to close the issue right now. Seems like all of my issues had already been addressed. Apologies for the noise.

**Comment by sickill** [comment]
No problem! I really appreciate your feedback. Feel free send more if you notice something.
