### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by TApplencourt** [asciinema/asciinema#87]
Hi,

I don't know if the problem is mine or your so sorry if it is all my fault.
`Error: Connection failed (Post https://asciinema.org/api/asciicasts: dial tcp: lookup asciinema.org: no such host)`

And i really don't know what to do. 

Thx for any information :)

**Comment by sickill** [comment]
`lookup asciinema.org: no such host` suggests DNS lookup issue on your side. Can you access `https://asciinema.org` in the browser?

**Comment by TApplencourt** [comment]
Yep. 
But i can't go to `https://asciinema.org/api/asciicasts`

**Comment by sickill** [comment]
@TApplencourt what OS are you using?

**Comment by TApplencourt** [comment]
Linux Mint 17 Qiana (Debian based)

**Comment by sickill** [comment]
And what version of asciinema? `asciinema --version`

**Comment by TApplencourt** [comment]
`asciinema 0.9.9-0eee9b2`
Should i update to 1.* beta ?

**Comment by sickill** [comment]
No need. Nothing related to API connection changed recently.

Can you run this in a terminal? `host asciinema.org`

**Comment by TApplencourt** [comment]
```
asciinema.orG has address 109.107.38.78
asciinema.org mail is handled by 30 ASPMX3.GOOGLEMAIL.COM.
asciinema.org mail is handled by 20 ALT1.ASPMX.L.GOOGLE.COM.
asciinema.org mail is handled by 20 ALT2.ASPMX.L.GOOGLE.COM.
asciinema.org mail is handled by 30 ASPMX2.GOOGLEMAIL.COM.
asciinema.org mail is handled by 10 ASPMX.L.GOOGLE.COM.
```

Only the .or**G** seem strange to me >.>

**Comment by sickill** [comment]
Yeah, this looks *strange* to me as well. I have it as `asciinema.org has address 109.107.38.78`, as it should be, so there's definitely something wrong with your DNS.

**Comment by TApplencourt** [comment]
Ok, i will fixe this. Thanks for all this quick reply!
