### ISSUE TITLE
Gentoo package

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#88]
The progress of packaging latest asciinema for Gentoo can be tracked here: https://bugs.gentoo.org/show_bug.cgi?id=532918

**Comment by Dr-Terrible** [comment]
Since Gentoo developers seem reluctant to add Go packages to _Portage_, I have created a Portage overlay specifically for packages written in GoLang: https://github.com/Dr-Terrible/go-overlay

Despite what Michael "kensington" Palimaka said in bugs.gentoo.org, there is a straightforward way to handle the GoLang toolchain and the complexity of its dependency chain. My overlay does exactly that, and in an automated way.

All you need to do to install asciinema 1.1.0+ is to sync my overlay and then execute a simple:

<pre>emerge -av dev-go/asciinema</pre>

I'd be glad to maintain _asciinema_ in my overlay if upstream is not willing.

**Comment by sickill** [comment]
That's great, thanks!

I have updated docs on the site to include your overlay: https://github.com/asciinema/asciinema.org/commit/fd7ec57d7a8644fd4a4576cabe2ddbfb3a705981
Is this the simplest way to add an overlay, or these instructions can be simpler?

**Comment by Dr-Terrible** [comment]
> That's great, thanks!

You're welcome.

> Is this the simplest way to add an overlay, or these instructions can be simpler?

Yeah, those instructions are the simplest way for adding an external overlay. Unfortunately there aren't shortcuts for these kind of tasks in _Gentoo_: https://wiki.gentoo.org/wiki/Project:Overlays/User_Guide#Getting_Started_With_Overlays

The only way to bypass _wget_ (and the manual regeneration of the local cache of _Layman_) is by adding my overlay to https://overlays.gentoo.org . That way the instructions will boil down to a mere:

<pre>layman -a go-overlay
emerge -av asciinema</pre>

I have officially made a request for the inclusion of my overlay into _Layman_'s list of repositories (unfortunately, some considerable delay should be expected from upstream): https://bugs.gentoo.org/552918

When my request will be fulfilled, you can safely update the docs with the two aforementioned commands.

**Comment by sickill** [comment]
Sounds good. Can you let me know when this happens so I can update the docs?

**Comment by Dr-Terrible** [comment]
> Can you let me know when this happens so I can update the docs?

Sure. As soon as my overlay has been added to Layman's repositories.xml, I'll post here a note.

**Comment by Dr-Terrible** [comment]
Done! The overlay has been added to http://overlay.gentoo.org. @sickill feel free to update asciinema's documentation.

**Comment by sickill** [comment]
@Dr-Terrible awesome.

Should it be now `emerge -av asciinema` or `emerge -av dev-go/asciinema`?

**Comment by Dr-Terrible** [comment]
I kept the original nomenclature from _Portage_'s tree to avoid points of friction / confusion for the final users, so `(sudo) emerge -av asciinema` or `(sudo) emerge -av app-misc/asciinema` are both perfectly fine.

This way, _asciinema_ package from my overlay will act as a standard and completely transparent update (from 0.9.8 to 1.1.1) for all the Gentoo users.

**Comment by sickill** [comment]
Nice. Thanks for your work!

**Comment by Dr-Terrible** [comment]
You're welcome.
I’m glad I was able to help. :)
