### ISSUE TITLE
Private recordings?

### ISSUE THREAD

**Issue by nootropics** [asciinema/asciinema#93]
Love the site but for just under a year we've been promised private recordings, I get it's not easy but surely it's not that hard just recoding/uploading and not indexing it on the main site?

**Comment by sickill** [comment]
I don't think I have promised anything to you or to anybody. I'm working on this project in my spare time (which I don't have as much as I'd like to have), and there are plenty of things me or other asciinema users would like to have implemented.

If you'd like to help the project please look here: https://asciinema.org/contributing
