### ISSUE TITLE
Ability to convert recorded sessions to different formats

### ISSUE THREAD

**Issue by Unode** [asciinema/asciinema#96]
Currently there's the upload option which takes care of making it available as a "video".
However there are situations where you may not want to make it public.

With that said, are there any plans to include ability to export the recorded session as different formats? I'm thinking GIF or a series of PNG/JPEG files that could then be converted to a video with ffmpeg or imagemagick.

**Comment by sickill** [comment]
@Unode there is no plan to build a converter at the moment. However if the fact that all asciicasts are public was the main problem here then you may like this: http://blog.asciinema.org/post/private/

**Comment by Unode** [comment]
@sickill Indeed private asciicasts is a nice feature but solves only part of the problem.

I'll keep my eyes out for future development on this front.
Thanks

**Comment by varac** [comment]
I'd like to request this feature nontheless, because it would be great to be able to show asciicinema offline, i.e. when you do a presentation and don't have internet available.

**Comment by sickill** [comment]
You have couple of options now:

- use self-hosted player: https://github.com/asciinema/asciinema-player
- convert your recording to gif: https://github.com/asciinema/asciicast2gif
